(function() {

  /***************************************************************************************************/
  /**************************** PREPARATION CODE *****************************************************/
  /***************************************************************************************************/

  // Browse companies listed as parameter by UUID & Name and get all investments & acquisitions from CrunchBase APIs
  function getInvestmentsAcquisitionsByCompanies(p_companyList, p_table) {
    // Iterate for as many companies as listed above
    for (var i = 0, len = p_companyList.length; i < len; i++) {
      var Sector = p_companyList[i].Sector;
      var Group = p_companyList[i].Group;
      var Company = p_companyList[i].Company;
      var Investor = p_companyList[i].Investor;
      var UUID = p_companyList[i].UUID;

      // GET INVESTMENTS DATA
      var PageNo = 1;
      var Next_page_url = "init";
      do {
        $.ajax({
          url: "https://api.crunchbase.com/v3.1/organizations/" + UUID + "/investments?user_key=9df45b533650fb1b95e83357b5da2db3&items_per_page=250&page=" + PageNo, // browse the list of investments
          async: false,
          indexValue: {
            paramSector: Sector,
            paramGroup: Group,
            paramCompany: Company,
            paramInvestor: Investor
          }, // to get Investor value from out of the ajaxCall
          success: function(response) {
            var investmentsJSON = response.data.items;
            var investmentTableData = [];
            for (var iI = 0, leniI = investmentsJSON.length; iI < leniI; iI++) {
              var Announced_Date = investmentsJSON[iI].properties.announced_on;
              var MoneyRaised = investmentsJSON[iI].relationships.funding_round.properties.money_raised_usd;
              if (MoneyRaised == null) MoneyRaised = 0;
              var FundingRoundType = investmentsJSON[iI].relationships.funding_round.type;
              var FundingType = investmentsJSON[iI].relationships.funding_round.properties.funding_type;
              var Series = investmentsJSON[iI].relationships.funding_round.properties.series;
              if (Series == null) Series = "";
              var FinalFundingType = FundingRoundType + " " + FundingType + " " + Series;
              var FundedCompany = investmentsJSON[iI].relationships.funding_round.relationships.funded_organization.properties.name;
              var FundedCompanyUUID = investmentsJSON[iI].relationships.funding_round.relationships.funded_organization.uuid;
              var ShortDescription = investmentsJSON[iI].relationships.funding_round.relationships.funded_organization.properties.short_description;
              var Description = investmentsJSON[iI].relationships.funding_round.relationships.funded_organization.properties.description;

              investmentTableData.push({
                "sector": this.indexValue.paramSector,
                "group": this.indexValue.paramGroup,
                "company": this.indexValue.paramCompany,
                "investor": this.indexValue.paramInvestor, // to get Investor value from out of the ajaxCall
                "transaction_type": "Investment",
                "funding_type": FinalFundingType,
                "money_raised": MoneyRaised,
                "announced_date": Announced_Date,
                "company_name_JOIN": FundedCompany,
                "target_company": FundedCompany,
                "short_description": ShortDescription,
                "description": Description
              });
            }
            p_table.appendRows(investmentTableData);
            Next_page_url = response.data.paging.next_page_url;
          }
        });
        PageNo++;
      }
      while (Next_page_url != null)

      // GET ACQUISITIONS DATA
      var PageNo2 = 1;
      var Next_page_url2 = "init";
      do {
        $.ajax({
          url: "https://api.crunchbase.com/v3.1/organizations/" + UUID + "/acquisitions?user_key=9df45b533650fb1b95e83357b5da2db3&items_per_page=250&page=" + PageNo2, // browse the list of acquisitions
          async: false,
          indexValue: {
            paramSector: Sector,
            paramGroup: Group,
            paramCompany: Company,
            paramInvestor: Investor
          }, // to get Investor value from out of the ajaxCall
          success: function(response2) {
            var acquisitionsJSON = response2.data.items;
            var acquisitionTableData = [];
            for (var iA = 0, leniA = acquisitionsJSON.length; iA < leniA; iA++) {
              var Announced_Date = acquisitionsJSON[iA].properties.announced_on;
              var MoneyRaised = acquisitionsJSON[iA].properties.price_usd;
              if (MoneyRaised == null) MoneyRaised = 0;
              var AcquiredCompany = acquisitionsJSON[iA].relationships.acquiree.properties.name;
              var ShortDescription = acquisitionsJSON[iA].relationships.acquiree.properties.short_description;
              var Description = acquisitionsJSON[iA].relationships.acquiree.properties.description;

              acquisitionTableData.push({
                "sector": this.indexValue.paramSector,
                "group": this.indexValue.paramGroup,
                "company": this.indexValue.paramCompany,
                "investor": this.indexValue.paramInvestor, // to get Investor value from out of the ajaxCall
                "transaction_type": "Acquisition",
                "funding_type": "",
                "money_raised": MoneyRaised,
                "announced_date": Announced_Date,
                "company_name_JOIN": AcquiredCompany,
                "target_company": AcquiredCompany,
                "short_description": ShortDescription,
                "description": Description
              });
            }
            p_table.appendRows(acquisitionTableData);
            Next_page_url2 = response2.data.paging.next_page_url;
          }
        });
        PageNo2++;
      } while (Next_page_url2 != null)
    }
  }

  // Inserts HARDCODED partnerships into the same table as Investments/Acquisitions
  function insertPartnerships(p_table) {
    var PartnershipsList = [
      {Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"AmazonCS",Company1:"Amazon"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Supplier",CompanyNameJOIN:"Here Technologies",Company1:"Here Technologies"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"what3words",Company1:"what3words"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Supplier",CompanyNameJOIN:"AT&T",Company1:"AT&T"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"ChargePoint",Company1:"ChargePoint"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"QualcommCEC",Company1:"Qualcomm"},
{Sector:"OEM",Group:"KIA",Company:"Kia",Investor:"Kia",TransactionType:"Partnership",CompanyNameJOIN:"Vodafone",Company1:"Vodafone"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"Vodafone",Company1:"Vodafone"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Walmart",Company1:"Walmart"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"Otonomo",Company1:"Otonomo"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"Deepglint",Company1:"Deepglint"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Soundhound Inc.",Company1:"Soundhound Inc."},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"Soundhound Inc.",Company1:"Soundhound Inc."},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Shell",Company1:"Shell"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"ParkMobile",Company1:"ParkMobile"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"DaimlerCS",Company1:"Daimler"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Aurora",Company1:"Aurora"},
{Sector:"OEM",Group:"Byton",Company:"Byton",Investor:"Byton",TransactionType:"Partnership",CompanyNameJOIN:"Aurora",Company1:"Aurora"},
{Sector:"OEM",Group:"KIA",Company:"Kia",Investor:"Kia",TransactionType:"Partnership",CompanyNameJOIN:"Vulog",Company1:"Vulog"},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"Vulog",Company1:"Vulog"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Cleenup",Company1:"Cleenup"},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"HuaweiCEC",Company1:"Huawei"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Uber",Company1:"Uber"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Uber",Company1:"Uber"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"Bosch",Company1:"Bosch"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"Uber",Company1:"Uber"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Aurora",Company1:"Aurora"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Continental",Company1:"Continental"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Delphi",Company1:"Delphi"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Intel",Company1:"Intel"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Lyft",Company1:"Lyft"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Mobileye",Company1:"Mobileye"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Microsoft",Company1:"Microsoft"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Mobileye",Company1:"Mobileye"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Google",Company1:"Google"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Google",Company1:"Google"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Microsoft",Company1:"Microsoft"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"JLR",Company1:"JLR"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Alibaba",Company1:"Alibaba"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Alibaba",Company1:"Alibaba"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Alibaba",Company1:"Alibaba"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"IBM",Company1:"IBM"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"IBM",Company1:"IBM"},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"IBM",Company1:"IBM"},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"Valeo",Company1:"Valeo"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"HuaweiCEC",Company1:"Huawei"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"Vodafone",Company1:"Vodafone"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"Siemens",Company1:"Siemens"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"QualcommAE",Company1:"Qualcomm"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Didi Chuxing",Company1:"Didi Chuxing"},
{Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"YandexN",Company1:"Yandex"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"YandexN",Company1:"Yandex"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Tomtom",Company1:"Tomtom"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Microsoft",Company1:"Microsoft"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"NASA",Company1:"NASA"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"DeNA",Company1:"DeNA"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Didi Chuxing",Company1:"Didi Chuxing"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"HuaweiS",Company1:"Huawei"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Microsoft",Company1:"Microsoft"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Ford",Company1:"Ford"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"BMW",Company1:"BMW"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"ChargePoint",Company1:"ChargePoint"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Engie",Company1:"Engie"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Enel",Company1:"Enel"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"EVgo",Company1:"EVgo"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"EVgo",Company1:"EVgo"},
{Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",TransactionType:"Partnership",CompanyNameJOIN:"Panasonic",Company1:"Panasonic"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Panasonic",Company1:"Panasonic"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"CATL",Company1:"CATL"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Samsung SDI",Company1:"Samsung SDI"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"CATL",Company1:"CATL"},
{Sector:"OEM",Group:"VAG",Company:"Porsche",Investor:"Porsche",TransactionType:"Partnership",CompanyNameJOIN:"Chargetrip",Company1:"Chargetrip"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Disney",Company1:"Disney"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"INRIX",Company1:"INRIX"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"AmazonS",Company1:"Amazon"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Pizza Hut",Company1:"Pizza Hut"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Dominos",Company1:"Dominos"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Supplier",CompanyNameJOIN:"Zenuity",Company1:"Zenuity"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Baidu",Company1:"Baidu"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"AmazonS",Company1:"Amazon"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Luminar",Company1:"Luminar"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Luminar",Company1:"Luminar"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"HuaweiADS",Company1:"Huawei"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Airbus",Company1:"Airbus"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"YandexADS",Company1:"Yandex"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Garmin",Company1:"Garmin"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Lidl",Company1:"Lidl"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Kaufland",Company1:"Kaufland"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Vulog",Company1:"Vulog"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"DaimlerADS",Company1:"Daimler"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"BMW",Company:"Mini",Investor:"Mini",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"BMW",Company:"Mini",Investor:"Mini",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Audible",Company1:"Audible"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Xevo",Company1:"Xevo"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"Xevo",Company1:"Xevo"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Xevo",Company1:"Xevo"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"Wind River",Company1:"Wind River"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Tencent",Company1:"Tencent"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Baidu",Company1:"Baidu"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"BYD",Company1:"BYD"}
    ];

    var partnershipsTableData = [];
    for (var i = 0, len = PartnershipsList.length; i < len; i++) {
      partnershipsTableData.push({
        "sector": PartnershipsList[i].Sector,
        "group": PartnershipsList[i].Group,
        "company": PartnershipsList[i].Company,
        "investor": PartnershipsList[i].Investor,
        "transaction_type": PartnershipsList[i].TransactionType,
        "funding_type": "",
        "money_raised": "",
        "announced_date": "",
        "company_name_JOIN": PartnershipsList[i].CompanyNameJOIN,
        "target_company": PartnershipsList[i].Company1,
        "short_description": "",
        "description": ""
      });
    }
    p_table.appendRows(partnershipsTableData);
  }

  // Inserts HARDCODED subsidiaries into the same table as Investments/Acquisitions
  function insertSubsidiaries(p_table) {
    var SubsidiariesList = [
      {Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Subsidiary",CompanyNameJOIN:"ShareNow",AnnouncedDate:"2019-01-01"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Subsidiary",CompanyNameJOIN:"ShareNow",AnnouncedDate:"2019-01-01"},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Subsidiary",CompanyNameJOIN:"Free2Move",AnnouncedDate:""},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Subsidiary",CompanyNameJOIN:"Free2Move Paris",AnnouncedDate:""},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Subsidiary",CompanyNameJOIN:"eMov",AnnouncedDate:""},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Subsidiary",CompanyNameJOIN:"WeShare",AnnouncedDate:""},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Subsidiary",CompanyNameJOIN:"Hive",AnnouncedDate:""},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Subsidiary",CompanyNameJOIN:"Hive",AnnouncedDate:""}
    ];

    var subsidiariesTableData = [];
    for (var i = 0, len = SubsidiariesList.length; i < len; i++) {
      subsidiariesTableData.push({
        "sector": SubsidiariesList[i].Sector,
        "group": SubsidiariesList[i].Group,
        "company": SubsidiariesList[i].Company,
        "investor": SubsidiariesList[i].Investor,
        "transaction_type": SubsidiariesList[i].TransactionType,
        "funding_type": "",
        "money_raised": "",
        "announced_date": SubsidiariesList[i].AnnouncedDate,
        "company_name_JOIN": SubsidiariesList[i].CompanyNameJOIN,
        "target_company": SubsidiariesList[i].CompanyNameJOIN,
        "short_description": "",
        "description": ""
      });
    }
    p_table.appendRows(subsidiariesTableData);
  }

  /***************************************************************************************************/
  /******************************** RUNNING CODE *****************************************************/
  /***************************************************************************************************/

  var myConnector = tableau.makeConnector();

  // When you create multiple table schemas, the WDC API calls the getData function once for each schema.
  myConnector.getSchema = function(schemaCallback) {

    // Transactions : Investments & Acquisitions
    var Transactions_cols = [
    {
      id: "sector",
      alias: "Sector",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "group",
      alias: "Group",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "company",
      alias: "Company",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "investor",
      alias: "Investor",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "transaction_type",
      alias: "Transaction Type",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "funding_type",
      alias: "Funding Type",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "money_raised",
      alias: "Money Raised",
      dataType: tableau.dataTypeEnum.int
    }, {
      id: "announced_date",
      alias: "Announced Date",
      dataType: tableau.dataTypeEnum.date
    }, {
      id: "company_name_JOIN",
      alias: "Company Name JOIN",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "target_company",
      alias: "Target Company",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "short_description",
      alias: "Short Description",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "description",
      alias: "Description",
      dataType: tableau.dataTypeEnum.string
    }
    ];
    var Transactions_Schema = {
      id: "Transactions", // table.tableInfo.id
      alias: "Transactions",
      columns: Transactions_cols
    };

    // Categories : Companies and their categories, coming from StartUp Flow
    var Categories_cols = [
    {
      id: "company_name_JOIN",
      alias: "Company Name JOIN",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "subcategory",
      alias: "Sub Category",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "category",
      alias: "Category",
      dataType: tableau.dataTypeEnum.string
    }
    ];
    var Categories_Schema = {
      id: "Categories", // table.tableInfo.id
      alias: "Categories",
      columns: Categories_cols
    };

    // It's only when several schemas are passed to this function that the getData function is called several times
    schemaCallback([Transactions_Schema,Categories_Schema]);
  };

  // When you create multiple table schemas, the WDC API calls the getData function once for each schema.
  // As a result, you need a way to change the call to the API for each table. The easiest way to do this is to use the table.tableInfo.id value that we set in the table schemas.
  myConnector.getData = function(table, doneCallback) {

    if (table.tableInfo.id == "Transactions") {
      var CompaniesList = [
        {Sector:"OEM",Group:"Alliance RNM",Company:"Alliance",Investor:"Renault Nissan Mitsubishi",UUID:"96fa22e600c4656428f64b2066e4021d"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Alliance",Investor:"Alliance Ventures",UUID:"bded51bc070240d5ba0e6771d44c5146"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi Motors",UUID:"fe8f7d6b2f90470223b5d7f18ca63a51"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi Electric",UUID:"2e1e8791e661a34d9a78bcabfdd1825f"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi UFJ Financial Group",UUID:"d4974159c3765f1b93c50cc0c187423b"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi Corporation",UUID:"b8d382916018dd9083ec0723756f2949"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi UFJ Capital",UUID:"d300b7548f03f143a08309c355f716ba"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Bank Of Tokyo - Mitsubishi UFJ",UUID:"453bb5c7da0798805c29a960edbb0676"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi International Corporation (MIC)",UUID:"176c343305f21c86a44393949ae65681"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Nissan",Investor:"Nissan Motor Corporation",UUID:"718eb41ba3098cd45e019958ac876ee5"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Renault",Investor:"Renault",UUID:"96ff3fd230b3249437059d861033a53e"},
        {Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",UUID:"b462608d8bf493f14f68e41ee10f0df2"},
        {Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW i Ventures",UUID:"0e35699837f1d2b1b6eb2b62cf418b3e"},
        {Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",UUID:"5d6ed201f03268afb4227e7c68129485"},
        {Sector:"Mobility",Group:"Didi Chuxing",Company:"Didi",Investor:"Didi Chuxing",UUID:"eab915a8f41464e05138c5f341596a5b"},
        {Sector:"OEM",Group:"FCA",Company:"Fiat",Investor:"FIAT S.p.A",UUID:"e7b7f5416f80e13f335f3b0932884c4c"},
        {Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford Motor Company",UUID:"9249e8b6409aa80c1a1e29ae21b1db47"},
        {Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford Foundation",UUID:"0ee8cd71bfd9bf6bfb96a38012b1e001"},
        {Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford Smart Mobility",UUID:"e5a7c1b5702f9efe3e3ebacc0e5e654c"},
        {Sector:"OEM",Group:"Geely",Company:"Geely",Investor:"Zhejiang Geely Holding Group",UUID:"cbcae3286143e6a215efd8b736ca9fff"},
        {Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo Group Venture Capital",UUID:"9a59d1e9d183001585270a39d01a9bfc"},
        {Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo Cars Group",UUID:"1894c8007d82904566067461508339da"},
        {Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo Cars Tech Fund",UUID:"86d2a05fdff04a4cbccb9f467e5ecc6e"},
        {Sector:"OEM",Group:"GM",Company:"GM",Investor:"General Motors Investment Management",UUID:"a1d14b6f137ebeaa847a8ba7ad65b4ea"},
        {Sector:"OEM",Group:"GM",Company:"GM",Investor:"General Motors",UUID:"5087a04780c54aa3dfdf30dd8ac88b5e"},
        {Sector:"OEM",Group:"GM",Company:"GM",Investor:"General Motors Ventures",UUID:"759be29a69e1615d373f8f8d8f020591"},
        {Sector:"Mobility",Group:"Grab",Company:"Grab",Investor:"Grab",UUID:"a76824768a83dbcf73dc41a841ef850e"},
        {Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda Motor",UUID:"0017e370d941822e83bc538beaab28da"},
        {Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai Motor Company",UUID:"271e1bf5086adbb89806b76a591b864e"},
        {Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai Venture Investment Corporation",UUID:"994661433b9eb9fc9283116b7b32af5a"},
        {Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"Jaguar Land Rover",UUID:"4b6fd457050953c1db591f694f5ef77b"},
        {Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"Jaguar Ventures",UUID:"75213e229421b3687e50a36e9ddf1cec"},
        {Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"Jaguar Land Rover’s venture capital fund",UUID:"ec11c33226e64c7db12a92b9305cf0dd"},
        {Sector:"OEM",Group:"KIA",Company:"Kia",Investor:"Kia Motors",UUID:"396458db49b8888dfba24953402d3d66"},
        {Sector:"Mobility",Group:"Lyft",Company:"Lyft",Investor:"Lyft",UUID:"33a97e70f137e90f8d68950a043ee09f"},
        {Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA Group",UUID:"7c01753993a20640220b5b05a855210a"},
        {Sector:"OEM",Group:"PSA",Company:"Peugeot",Investor:"Peugeot SA",UUID:"ee1dec4f08abb10cd37aa27ef162d215"},
        {Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",UUID:"a367b036595254357541ad7ee8869e24"},
        {Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota Motor Corporation",UUID:"12b90373ab49a56a4b4ec7b3e9236faf"},
        {Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota Tsusho",UUID:"4ecb67dc639df5b6cd57da212250cebc"},
        {Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota AI Ventures",UUID:"4419828e7e06f10e323c4e985821dafd"},
        {Sector:"Mobility",Group:"Uber",Company:"Uber",Investor:"Uber",UUID:"1eb371093b9301a9177ffee2cb1bfcdc"},
        {Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen group",UUID:"8a2b18d24cfbac1708b207b01d092e2a"},
        {Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",UUID:"81a1ceaa081ffe4ffbb4ca4cbc8293a8"},
        {Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen We",UUID:"a31b34c32f6543789fb20993d74b4dad"},
        {Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen Financial Services",UUID:"5449c78f0a2a24b1c2f1414ec2e27917"},
        {Sector:"OEM",Group:"VAG",Company:"Porsche",Investor:"Porsche",UUID:"68255d6d16144c7c1a0b3d3998c1d2c2"},
        {Sector:"OEM",Group:"VAG",Company:"Porsche",Investor:"Porsche Automobil Holding",UUID:"8ea457a172805992c020e741fef4a8dc"},
        {Sector:"OEM",Group:"VAG",Company:"Seat",Investor:"Seat",UUID:"fdf2b2f2241533a054ad3b9755b84f33"},
        {Sector:"OEM",Group:"VAG",Company:"Škoda",Investor:"Škoda Auto a.s ",UUID:"7c71810f27514e8c95d7e2fae0b96178"}
      ];
      getInvestmentsAcquisitionsByCompanies(CompaniesList, table);
      insertPartnerships(table);
      insertSubsidiaries(table);
      doneCallback();
    }

    if (table.tableInfo.id == "Categories") {
      var CategoriesList = [
        {CompanyNameJOIN:"Carbon",SubCategory:"3D Printing",Category:"Others"},
{CompanyNameJOIN:"Desktop Metal",SubCategory:"3D Printing",Category:"Others"},
{CompanyNameJOIN:"Zebra Imaging",SubCategory:"3D technology",Category:"Others"},
{CompanyNameJOIN:"Revl",SubCategory:"Action Cam",Category:"Others"},
{CompanyNameJOIN:"Apex.AI",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"Argo AI",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"Aurora",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"Baidu",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"Cruise",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"DaimlerADS",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"HuaweiADS",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"NASA",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"Rivian Automotive",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"Waymo",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"Wind River",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"YandexADS",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"Zenuity",SubCategory:"AD Software",Category:"Autonomous"},
{CompanyNameJOIN:"Mcity",SubCategory:"AD Test simulator",Category:"Autonomous"},
{CompanyNameJOIN:"Parallel Domain",SubCategory:"AD Test simulator",Category:"Autonomous"},
{CompanyNameJOIN:"StradVision, Inc",SubCategory:"ADAS",Category:"Autonomous"},
{CompanyNameJOIN:"Valeo",SubCategory:"ADAS",Category:"Autonomous"},
{CompanyNameJOIN:"Nauto",SubCategory:"AI",Category:"Autonomous"},
{CompanyNameJOIN:"Preferred Networks",SubCategory:"AI",Category:"Connected"},
{CompanyNameJOIN:"WeRide.ai",SubCategory:"AI",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Graphcore",SubCategory:"AI components",Category:"Others"},
{CompanyNameJOIN:"Volocopter",SubCategory:"Air Mobility",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Via",SubCategory:"Autonomous VAN/Trucks",Category:"Autonomous"},
{CompanyNameJOIN:"DeepMap",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
{CompanyNameJOIN:"Lunewave",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
{CompanyNameJOIN:"May Mobility",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
{CompanyNameJOIN:"Metawave Corporation",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
{CompanyNameJOIN:"Momenta",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
{CompanyNameJOIN:"Perceptive Automata",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
{CompanyNameJOIN:"Starship Technologies",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
{CompanyNameJOIN:"Uber Advanced Technologies Group",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
{CompanyNameJOIN:"Velodyne LiDAR",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
{CompanyNameJOIN:"Continental",SubCategory:"Autonomy enablers",Category:"Autonomous"},
{CompanyNameJOIN:"Delphi",SubCategory:"Autonomy enablers",Category:"Autonomous"},
{CompanyNameJOIN:"DeNA",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
{CompanyNameJOIN:"IBM",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
{CompanyNameJOIN:"Intel",SubCategory:"Autonomy enablers",Category:"Autonomous"},
{CompanyNameJOIN:"Luminar",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
{CompanyNameJOIN:"Mobileye",SubCategory:"Autonomy enablers",Category:"Autonomous"},
{CompanyNameJOIN:"Nvidia",SubCategory:"Autonomy enablers",Category:"Autonomous"},
{CompanyNameJOIN:"QualcommAE",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
{CompanyNameJOIN:"Walmart",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
{CompanyNameJOIN:"CATL",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"Enevate",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"Envia Systems",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"Ionic Materials",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"JLR",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"Panasonic",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"Samsung SDI",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"Sila Nanotechnologies",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"SolidEnergy Systems",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"StoreDot",SubCategory:"Batteries",Category:"Electrification"},
{CompanyNameJOIN:"GaN Systems",SubCategory:"Battery technology",Category:"Electrification"},
{CompanyNameJOIN:"Sakti3",SubCategory:"Battery technology",Category:"Electrification"},
{CompanyNameJOIN:"Solid Power",SubCategory:"Battery technology",Category:"Electrification"},
{CompanyNameJOIN:"CARFIT",SubCategory:"Big Data",Category:"Connected"},
{CompanyNameJOIN:"Wejo",SubCategory:"Big Data",Category:"Connected"},
{CompanyNameJOIN:"ofo",SubCategory:"Bike-Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Bus.com",SubCategory:"Bus sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"FlixBus",SubCategory:"Bus sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Rally",SubCategory:"Bus sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Cleenup",SubCategory:"Car Cleening",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"SoundHound Inc.",SubCategory:"Car Control",Category:"Connected"},
{CompanyNameJOIN:"AT&T",SubCategory:"Car External Connections",Category:"Connected"},
{CompanyNameJOIN:"Deepglint",SubCategory:"Car External Connections",Category:"Connected"},
{CompanyNameJOIN:"HuaweiCEC",SubCategory:"Car External Connections",Category:"Connected"},
{CompanyNameJOIN:"Otonomo",SubCategory:"Car External Connections",Category:"Connected"},
{CompanyNameJOIN:"QualcommCEC",SubCategory:"Car External Connections",Category:"Connected"},
{CompanyNameJOIN:"Siemens",SubCategory:"Car External Connections",Category:"Connected"},
{CompanyNameJOIN:"Vodafone",SubCategory:"Car External Connections",Category:"Connected"},
{CompanyNameJOIN:"Blacklane",SubCategory:"Car Hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Summon",SubCategory:"Car Hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Fair",SubCategory:"Car Leasing",Category:"Others"},
{CompanyNameJOIN:"Bright Automotive",SubCategory:"Car Manufacturer",Category:"Electrification"},
{CompanyNameJOIN:"Mazda Motor Corp.",SubCategory:"Car Manufacturer",Category:"Others"},
{CompanyNameJOIN:"PROTON Holdings",SubCategory:"Car Manufacturer",Category:"Others"},
{CompanyNameJOIN:"Caroobi",SubCategory:"Car Marketplace",Category:"Others"},
{CompanyNameJOIN:"Shift",SubCategory:"Car Marketplace",Category:"Others"},
{CompanyNameJOIN:"Skurt",SubCategory:"Car Rental",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Yestock",SubCategory:"Car Rental",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"ZoomCar",SubCategory:"Car Rental",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Carventura",SubCategory:"Car Sales Platforms",Category:"Others"},
{CompanyNameJOIN:"99",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Car Next Door",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Careem",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"carpooling.com",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"DaimlerCS",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"eMov",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Free2Move Paris",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Getaround",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Revv",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"ShareNow",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Silvercar",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"TravelCar",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Turo",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"WeShare",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"feezu.cn",SubCategory:"Car Sharing Solution",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Chargemaster",SubCategory:"Charging Solution",Category:"Electrification"},
{CompanyNameJOIN:"Hubject",SubCategory:"Charging Solution",Category:"Electrification"},
{CompanyNameJOIN:"AmazonCS",SubCategory:"Charging Station",Category:"Electrification"},
{CompanyNameJOIN:"ChargePoint",SubCategory:"Charging Station",Category:"Electrification"},
{CompanyNameJOIN:"Enel",SubCategory:"Charging Station",Category:"Electrification"},
{CompanyNameJOIN:"Engie",SubCategory:"Charging Station",Category:"Electrification"},
{CompanyNameJOIN:"EVgo",SubCategory:"Charging Station",Category:"Electrification"},
{CompanyNameJOIN:"Ionity",SubCategory:"Charging Station",Category:"Electrification"},
{CompanyNameJOIN:"Kaufland",SubCategory:"Charging Station",Category:"Electrification"},
{CompanyNameJOIN:"Lidl",SubCategory:"Charging Station",Category:"Electrification"},
{CompanyNameJOIN:"Zum",SubCategory:"Child Transportation",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Yoshi",SubCategory:"Cleaning and gas services",Category:"Connected"},
{CompanyNameJOIN:"CloudCar",SubCategory:"Cloud",Category:"Connected"},
{CompanyNameJOIN:"Microsoft",SubCategory:"Cloud/Data Platforms",Category:"Others"},
{CompanyNameJOIN:"RenRenChe",SubCategory:"commerce",Category:"Others"},
{CompanyNameJOIN:"iBiquity Digital Corporation",SubCategory:"Connectivity",Category:"Connected"},
{CompanyNameJOIN:"Telcontar",SubCategory:"Connectivity",Category:"Connected"},
{CompanyNameJOIN:"Claroty",SubCategory:"Cybersecurity",Category:"Others"},
{CompanyNameJOIN:"Yellowbrick Data",SubCategory:"Data Management",Category:"Others"},
{CompanyNameJOIN:"Matternet",SubCategory:"Delivery",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"tiramizoo",SubCategory:"Delivery",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"MyCityWay",SubCategory:"Digital Platform",Category:"Others"},
{CompanyNameJOIN:"AutoGravity",SubCategory:"e-commerce",Category:"Others"},
{CompanyNameJOIN:"BeXcom Korea",SubCategory:"e-commerce",Category:"Others"},
{CompanyNameJOIN:"carClub",SubCategory:"e-commerce",Category:"Others"},
{CompanyNameJOIN:"HDS Global",SubCategory:"e-commerce",Category:"Others"},
{CompanyNameJOIN:"Heycar",SubCategory:"e-commerce",Category:"Others"},
{CompanyNameJOIN:"Tantau Software",SubCategory:"e-commerce",Category:"Others"},
{CompanyNameJOIN:"KnowledgeNet",SubCategory:"e-learning",Category:"Others"},
{CompanyNameJOIN:"Vantage Power",SubCategory:"Electric Engine",Category:"Electrification"},
{CompanyNameJOIN:"BAIC BJEV",SubCategory:"Electric Vehicles",Category:"Electrification"},
{CompanyNameJOIN:"BMW",SubCategory:"Electric Vehicles",Category:"Electrification"},
{CompanyNameJOIN:"Ford",SubCategory:"Electric Vehicles",Category:"Electrification"},
{CompanyNameJOIN:"Rimac",SubCategory:"Electric Vehicles",Category:"Electrification"},
{CompanyNameJOIN:"Tesla",SubCategory:"Electric Vehicles",Category:"Electrification"},
{CompanyNameJOIN:"Zhidou",SubCategory:"Electric Vehicles",Category:"Electrification"},
{CompanyNameJOIN:"Kalray",SubCategory:"Electronics",Category:"Others"},
{CompanyNameJOIN:"Prescient Markets",SubCategory:"Electronics",Category:"Others"},
{CompanyNameJOIN:"TTTech",SubCategory:"Electronics",Category:"Connected"},
{CompanyNameJOIN:"Alphabet Energy",SubCategory:"Energy production",Category:"Electrification"},
{CompanyNameJOIN:"Coskata",SubCategory:"Energy production",Category:"Electrification"},
{CompanyNameJOIN:"Mascoma",SubCategory:"Energy production",Category:"Electrification"},
{CompanyNameJOIN:"Northvolt",SubCategory:"Energy production",Category:"Electrification"},
{CompanyNameJOIN:"Virent Energy Systems",SubCategory:"Energy provider",Category:"Electrification"},
{CompanyNameJOIN:"QuantumScape",SubCategory:"Energy storage",Category:"Electrification"},
{CompanyNameJOIN:"Audible",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"Disney",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"Garmin",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"Spotify",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"TuneIn",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"eRoom Technology",SubCategory:"Enterprise Software",Category:"Others"},
{CompanyNameJOIN:"Pivotal",SubCategory:"Enterprise Software",Category:"Others"},
{CompanyNameJOIN:"Plumtree Software",SubCategory:"Enterprise Software",Category:"Others"},
{CompanyNameJOIN:"Sansan",SubCategory:"Enterprise Software",Category:"Others"},
{CompanyNameJOIN:"Joby Aviation",SubCategory:"e-Plane",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Hive",SubCategory:"e-scooter",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Immotor",SubCategory:"e-scooter",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Shouqi Zhixing",SubCategory:"e-scooter",Category:"Electrification"},
{CompanyNameJOIN:"Proterra",SubCategory:"EV Bus",Category:"Electrification"},
{CompanyNameJOIN:"Rimac Automobili",SubCategory:"EV Components",Category:"Electrification"},
{CompanyNameJOIN:"AutoFi",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"Saxo Bank",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"Spring Labs",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"STRATIM Systems",SubCategory:"Fleet Management",Category:"Others"},
{CompanyNameJOIN:"Zonar",SubCategory:"Fleet Management",Category:"Connected"},
{CompanyNameJOIN:"Mobile Go",SubCategory:"Food services",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Pixim",SubCategory:"Hardware",Category:"Others"},
{CompanyNameJOIN:"Hap2U",SubCategory:"HMI",Category:"Connected"},
{CompanyNameJOIN:"Tula Technology",SubCategory:"ICE Technology",Category:"Electrification"},
{CompanyNameJOIN:"Delta ID",SubCategory:"Identity Management",Category:"Connected"},
{CompanyNameJOIN:"Keyfactor",SubCategory:"Identity Management",Category:"Connected"},
{CompanyNameJOIN:"Omada",SubCategory:"Identity Management",Category:"Connected"},
{CompanyNameJOIN:"BioAmber",SubCategory:"Industry",Category:"Others"},
{CompanyNameJOIN:"AvantGo",SubCategory:"Internet",Category:"Connected"},
{CompanyNameJOIN:"Boxbot",SubCategory:"Last mile delivery",Category:"Autonomous"},
{CompanyNameJOIN:"Blackmore Sensors and Analytics",SubCategory:"Lidar solution",Category:"Autonomous"},
{CompanyNameJOIN:"GeoDigital",SubCategory:"Lidar solution",Category:"Autonomous"},
{CompanyNameJOIN:"Strobe",SubCategory:"Lidar solution",Category:"Autonomous"},
{CompanyNameJOIN:"Mesh Korea",SubCategory:"Logistic",Category:"Others"},
{CompanyNameJOIN:"Free2Move",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Migo",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Ola",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Ridecell",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Transit",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Vulog",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Maluuba",SubCategory:"Machine learning",Category:"Others"},
{CompanyNameJOIN:"SAIPS",SubCategory:"Machine learning",Category:"Others"},
{CompanyNameJOIN:"Tekion",SubCategory:"Machine learning",Category:"Others"},
{CompanyNameJOIN:"Xometry",SubCategory:"Manufacturing Solution",Category:"Others"},
{CompanyNameJOIN:"Mapillary",SubCategory:"Map",Category:"Connected"},
{CompanyNameJOIN:"Autobiz.fr",SubCategory:"Marketplace",Category:"Others"},
{CompanyNameJOIN:"Sirrus",SubCategory:"Material",Category:"Others"},
{CompanyNameJOIN:"Bolt",SubCategory:"Micro Mobility",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Flinc",SubCategory:"Micro Mobility",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Life360",SubCategory:"Mobile Application",Category:"Connected"},
{CompanyNameJOIN:"NanoSteel",SubCategory:"Nano Technology",Category:"Others"},
{CompanyNameJOIN:"SDC Materials,Inc.",SubCategory:"Nano Technology",Category:"Others"},
{CompanyNameJOIN:"Civil Maps",SubCategory:"Navigation",Category:"Connected"},
{CompanyNameJOIN:"deCarta",SubCategory:"Navigation",Category:"Connected"},
{CompanyNameJOIN:"HERE Technologies",SubCategory:"Navigation",Category:"Connected"},
{CompanyNameJOIN:"Telogis",SubCategory:"Navigation",Category:"Others"},
{CompanyNameJOIN:"Tomtom",SubCategory:"Navigation",Category:"Connected"},
{CompanyNameJOIN:"TransLoc",SubCategory:"Navigation",Category:"Connected"},
{CompanyNameJOIN:"Ushr",SubCategory:"Navigation",Category:"Autonomous"},
{CompanyNameJOIN:"what3words",SubCategory:"Navigation",Category:"Connected"},
{CompanyNameJOIN:"YandexN",SubCategory:"Navigation",Category:"Connected"},
{CompanyNameJOIN:"Chargetrip",SubCategory:"Others",Category:"Electrification"},
{CompanyNameJOIN:"Scoop Technologies",SubCategory:"P2P Carpooling",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"GottaPark",SubCategory:"Parking",Category:"Connected"},
{CompanyNameJOIN:"JustPark",SubCategory:"Parking",Category:"Connected"},
{CompanyNameJOIN:"ParkTAG",SubCategory:"Parking",Category:"Connected"},
{CompanyNameJOIN:"Coord",SubCategory:"Platform",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Catalytic Solutions",SubCategory:"Pollution Technology",Category:"Others"},
{CompanyNameJOIN:"Seurat Technologies",SubCategory:"Printing Solution",Category:"Others"},
{CompanyNameJOIN:"Embark",SubCategory:"Public Transportation app",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Airbus",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"CINQS",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Didi Chuxing",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Grab",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Intelligent Apps (mytaxi)",SubCategory:"Ride Hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"JapanTaxi",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Lyft",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Uber",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Caocao Zhuanche",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"flinc GmbH",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Gett",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Taxify",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Validated",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Elementary Robotics",SubCategory:"Robot",Category:"Others"},
{CompanyNameJOIN:"Spin",SubCategory:"Scooter Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Zendrive",SubCategory:"Sensors",Category:"Connected"},
{CompanyNameJOIN:"Alibaba",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"AmazonS",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Anagog",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Autonomic",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Bosch",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Dominos",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Garantibil",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Google",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"HuaweiS",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"INRIX",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"ParkMobile",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Parkmobile Group Europe",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Pizza Hut",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Shell",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Spring",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Tencent",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"WayRay",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Xevo",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Urgent.ly Roadside Assistance",SubCategory:"Services platform",Category:"Connected"},
{CompanyNameJOIN:"Via Transportation, Inc.",SubCategory:"Shuttle Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Miles",SubCategory:"Social Plateform",Category:"Connected"},
{CompanyNameJOIN:"Rever",SubCategory:"Social Plateform",Category:"Connected"},
{CompanyNameJOIN:"Black Girls CODE",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"Campus Pipeline",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"Girls Who Code",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"Ignite Sports Media",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"MapAnything",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"OpenSynergy",SubCategory:"Software",Category:"Connected"},
{CompanyNameJOIN:"Realtime Robotics",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"Sequence Design",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"Sital Technology",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"Vontu",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"Empower Energies Inc.",SubCategory:"Solar Energy",Category:"Electrification"},
{CompanyNameJOIN:"Sunlogics",SubCategory:"Solar Energy",Category:"Electrification"},
{CompanyNameJOIN:"DSP Concepts",SubCategory:"Sounds sensor",Category:"Autonomous"},
{CompanyNameJOIN:"Data Enlighten",SubCategory:"Space Travel",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"iSpace China",SubCategory:"Space Travel",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"SLAMcore",SubCategory:"Spatial AI",Category:"Others"},
{CompanyNameJOIN:"Broadlane",SubCategory:"Supply Chain",Category:"Others"},
{CompanyNameJOIN:"China Unicom",SubCategory:"Telecommunication",Category:"Others"},
{CompanyNameJOIN:"Moovit",SubCategory:"Transportation info",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Kamaz",SubCategory:"Trucks",Category:"Others"},
{CompanyNameJOIN:"Navistar",SubCategory:"Trucks",Category:"Others"},
{CompanyNameJOIN:"Apollo Voice",SubCategory:"VPA",Category:"Connected"},
{CompanyNameJOIN:"Mobvoi",SubCategory:"VPA",Category:"Connected"},
{CompanyNameJOIN:"Mycroft",SubCategory:"VPA",Category:"Connected"},
{CompanyNameJOIN:"STRIVR",SubCategory:"VR training",Category:"Others"},
{CompanyNameJOIN:"Powermat Technologies",SubCategory:"Wireless Charging",Category:"Electrification"},
{CompanyNameJOIN:"Autotalks",SubCategory:"Wireless Technology",Category:"Connected"},
{CompanyNameJOIN:"19pay",SubCategory:"E-payment",Category:"Connected"},
{CompanyNameJOIN:"3D Media",SubCategory:"3D technology",Category:"Others"},
{CompanyNameJOIN:"A8 Digital Music",SubCategory:"Music platform",Category:"Connected"},
{CompanyNameJOIN:"ABEJA",SubCategory:"AI",Category:"Autonomous"},
{CompanyNameJOIN:"Accelight Networks",SubCategory:"Optical system",Category:"Others"},
{CompanyNameJOIN:"Adero",SubCategory:"Object location",Category:"Connected"},
{CompanyNameJOIN:"Adexa",SubCategory:"Enterprise software",Category:"Others"},
{CompanyNameJOIN:"AdInnovation",SubCategory:"Mobile ads",Category:"Others"},
{CompanyNameJOIN:"Agility Communications",SubCategory:"Laser",Category:"Autonomous"},
{CompanyNameJOIN:"Aiming",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"Air2Web",SubCategory:"Mobile Application",Category:"Connected"},
{CompanyNameJOIN:"Akoustic Arts",SubCategory:"Sounds Technology",Category:"Connected"},
{CompanyNameJOIN:"Algolux",SubCategory:"Machine learning",Category:"Autonomous"},
{CompanyNameJOIN:"Allegro.AI",SubCategory:"AI",Category:"Others"},
{CompanyNameJOIN:"Alpaca",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"AlpacaJapan",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"Ambee (1st Consult Technologies)",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"AmeriCredit",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"Anaeropharma Science",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"Annuncio Software",SubCategory:"Enterprise software",Category:"Others"},
{CompanyNameJOIN:"Anthera Pharmaceuticals",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"Antrim Design Systems",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"AOS Mobile",SubCategory:"AI",Category:"Others"},
{CompanyNameJOIN:"Aperto Networks",SubCategory:"Wireless Technology",Category:"Connected"},
{CompanyNameJOIN:"Apollo Voice Assistant",SubCategory:"VPA",Category:"Connected"},
{CompanyNameJOIN:"AppyParking",SubCategory:"Parking",Category:"Connected"},
{CompanyNameJOIN:"Ardana Bioscience",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"ArrayComm",SubCategory:"Wireless Technology",Category:"Connected"},
{CompanyNameJOIN:"Aryballe Technologies",SubCategory:"Sensors",Category:"Autonomous"},
{CompanyNameJOIN:"ASTES4",SubCategory:"Automation",Category:"Others"},
{CompanyNameJOIN:"Astro Malaysia Holdings Berhad",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"AtomicTangerine",SubCategory:"Consulting",Category:"Others"},
{CompanyNameJOIN:"Audioburst",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"AutoAI",SubCategory:"AI",Category:"Autonomous"},
{CompanyNameJOIN:"Autobutler",SubCategory:"Marketplace",Category:"Others"},
{CompanyNameJOIN:"Automobile Craiova",SubCategory:"Car Manufacturer",Category:"Others"},
{CompanyNameJOIN:"AutoSpot",SubCategory:"Marketplace",Category:"Others"},
{CompanyNameJOIN:"Axiata",SubCategory:"Telecommunication",Category:"Connected"},
{CompanyNameJOIN:"BarterTrust.com",SubCategory:"Marketplace",Category:"Others"},
{CompanyNameJOIN:"Beat",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Ben & Frank",SubCategory:"Fashin",Category:"Others"},
{CompanyNameJOIN:"BeneStream",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"BioMimetic Therapeutics",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"bitFlyer",SubCategory:"Crypto-currency",Category:"Others"},
{CompanyNameJOIN:"Blue Vision Labs",SubCategory:"AR",Category:"Connected"},
{CompanyNameJOIN:"Bluegogo",SubCategory:"bike-sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"BoostWorks",SubCategory:"Network Technology",Category:"Connected"},
{CompanyNameJOIN:"Brandtrack",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"Breeze",SubCategory:"E-payment",Category:"Connected"},
{CompanyNameJOIN:"Brigad",SubCategory:"Staffing Agency",Category:"Others"},
{CompanyNameJOIN:"Butterfield Fulcrum",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"BYD",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"Cadillac",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"Cadre",SubCategory:"",Category:""},
{CompanyNameJOIN:"Cambrios Technologies",SubCategory:"Screen technology",Category:"Others"},
{CompanyNameJOIN:"Caocao Chuxing",SubCategory:"Ride-Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Cape Wind",SubCategory:"Energy production",Category:"Electrification"},
{CompanyNameJOIN:"Capital Analytics",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"Capy Inc.",SubCategory:"Cybersecurity",Category:"Connected"},
{CompanyNameJOIN:"Cara Therapeutics",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"Cardiac Dimensions",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"Cargomatic",SubCategory:"Geolocalisation",Category:"Connected"},
{CompanyNameJOIN:"CARIZY",SubCategory:"Car Marketplace",Category:"Others"},
{CompanyNameJOIN:"Carventura SAS",SubCategory:"Services",Category:"Others"},
{CompanyNameJOIN:"Carwow",SubCategory:"Car Marketplace",Category:"Others"},
{CompanyNameJOIN:"Cascade Corporation",SubCategory:"Enterprise software",Category:"Others"},
{CompanyNameJOIN:"Cermaq",SubCategory:"Agriculture",Category:"Others"},
{CompanyNameJOIN:"CETITEC",SubCategory:"Software development",Category:"Others"},
{CompanyNameJOIN:"Chainalysis",SubCategory:"Crypto-currency",Category:"Others"},
{CompanyNameJOIN:"Challenge Media Group",SubCategory:"Software development",Category:"Others"},
{CompanyNameJOIN:"Chariot",SubCategory:"Van Pooling",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Checkars",SubCategory:"Car Marketplace",Category:"Others"},
{CompanyNameJOIN:"Cherry",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Chordia Therapeutics",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"CINTEO GmbH",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"ClimaCell",SubCategory:"Weather",Category:"Connected"},
{CompanyNameJOIN:"Cohesive Technologies",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"Coinbase",SubCategory:"Crypto-currency",Category:"Others"},
{CompanyNameJOIN:"Commerx Corp.",SubCategory:"Telecommunication",Category:"Connected"},
{CompanyNameJOIN:"Complex Polygon",SubCategory:"Mobile Application",Category:"Connected"},
{CompanyNameJOIN:"Conekta",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"Crowd Realty",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"Cswitch",SubCategory:"Hardware",Category:"Others"},
{CompanyNameJOIN:"CureApp",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"CyberHeart",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"Daihatsu",SubCategory:"Engine Manufacturer",Category:"Others"},
{CompanyNameJOIN:"Daimler",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"DataChassi DC AB",SubCategory:"Alartm",Category:"Others"},
{CompanyNameJOIN:"DataScore",SubCategory:"Big Data",Category:"Others"},
{CompanyNameJOIN:"Dejima",SubCategory:"VPA",Category:"Connected"},
{CompanyNameJOIN:"Devialet",SubCategory:"Sounds",Category:"Connected"},
{CompanyNameJOIN:"D-ID",SubCategory:"ID management",Category:"Connected"},
{CompanyNameJOIN:"DiscGenics",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"DriveNow GmbH & Co. KG",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Droom Technology",SubCategory:"Marketplace",Category:"Others"},
{CompanyNameJOIN:"eBags.com",SubCategory:"e-commerce",Category:"Connected"},
{CompanyNameJOIN:"EDS (Electronic Data Systems)",SubCategory:"Enterprise software",Category:"Others"},
{CompanyNameJOIN:"e-LogiT",SubCategory:"e-commerce",Category:"Connected"},
{CompanyNameJOIN:"Embodied, Inc.",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"Emerald Automotive",SubCategory:"EV technology",Category:"Electrification"},
{CompanyNameJOIN:"Encryptix",SubCategory:"Cloud",Category:"Others"},
{CompanyNameJOIN:"Engs Commercial Finance",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"Entuity",SubCategory:"Network Technology",Category:"Connected"},
{CompanyNameJOIN:"Eurus Energy Holdings",SubCategory:"Energy production",Category:"Electrification"},
{CompanyNameJOIN:"EXest",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"FA Tech Co Ltd.",SubCategory:"Machinery Manufacturing",Category:"Others"},
{CompanyNameJOIN:"Fiat Chrysler Automobiles",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"FinitePaths Inc.",SubCategory:"Services",Category:"Connected"},
{CompanyNameJOIN:"Flexitech Holding",SubCategory:"Car components",Category:"Others"},
{CompanyNameJOIN:"FlixMobility",SubCategory:"Bus-Sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Fonderie Aluminium Cleon",SubCategory:"Car components",Category:"Others"},
{CompanyNameJOIN:"Forciot",SubCategory:"IOT",Category:"Others"},
{CompanyNameJOIN:"Freedom Robotics",SubCategory:"Robotics",Category:"Others"},
{CompanyNameJOIN:"freee",SubCategory:"Financial Services",Category:"Others"},
{CompanyNameJOIN:"FreeWire Technologies",SubCategory:"Charging Technology",Category:"Electrification"},
{CompanyNameJOIN:"Gadauto",SubCategory:"Car retailer",Category:"Others"},
{CompanyNameJOIN:"Gaudena",SubCategory:"e-commerce",Category:"Connected"},
{CompanyNameJOIN:"Gengo",SubCategory:"Translator",Category:"Connected"},
{CompanyNameJOIN:"Geometric Intelligence",SubCategory:"AI",Category:"Autonomous"},
{CompanyNameJOIN:"GM Financial",SubCategory:"OEM",Category:"others"},
{CompanyNameJOIN:"GOJEK",SubCategory:"Mobility Provider",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Grohmann Engineering",SubCategory:"Car Manufacturer",Category:"Others"},
{CompanyNameJOIN:"H2scan",SubCategory:"Hydrogen technlogy",Category:"Electrification"},
{CompanyNameJOIN:"Hans Glas",SubCategory:"Car Manufacturer",Category:"Others"},
{CompanyNameJOIN:"Hibernia Networks",SubCategory:"Telecommunication",Category:"Others"},
{CompanyNameJOIN:"Hino Ottawa-Gatineau",SubCategory:"Car Manufacturer",Category:"Others"},
{CompanyNameJOIN:"Hitch",SubCategory:"",Category:""},
{CompanyNameJOIN:"HoloEyes",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"Humanigen",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"Hydrogenious Technologies",SubCategory:"Hydrogen technlogy",Category:"Electrification"},
{CompanyNameJOIN:"ICONICS",SubCategory:"Software development",Category:"Others"},
{CompanyNameJOIN:"iKaaz",SubCategory:"E-payment",Category:"Connected"},
{CompanyNameJOIN:"Illuminate Labs",SubCategory:"Gaming",Category:"Connected"},
{CompanyNameJOIN:"Infolibria",SubCategory:"Entertainment",Category:"Connected"},
{CompanyNameJOIN:"Informative",SubCategory:"Advertising",Category:"Others"},
{CompanyNameJOIN:"Intelligent Apps",SubCategory:"Ride-hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Intuition Robotics",SubCategory:"Robotics",Category:"Others"},
{CompanyNameJOIN:"iPierian",SubCategory:"Health services",Category:"Others"},
{CompanyNameJOIN:"iRidge",SubCategory:"Advertising",Category:"Others"},
{CompanyNameJOIN:"I-Tech",SubCategory:"Chemical",Category:"Others"},
{CompanyNameJOIN:"Jaguar",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"Jedlix",SubCategory:"Charging Technology",Category:"Electrification"},
{CompanyNameJOIN:"JIMU Intelligent",SubCategory:"Software",Category:"Autonomous"},
{CompanyNameJOIN:"Journey Holding Corporation",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"JTOWER Inc.",SubCategory:"Software",Category:"Others"},
{CompanyNameJOIN:"JUMP Bikes",SubCategory:"bike-sharing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"JX PRESS",SubCategory:"",Category:""},
{CompanyNameJOIN:"Kamcord",SubCategory:"",Category:""},
{CompanyNameJOIN:"KH-Automation Projects GmbH",SubCategory:"",Category:""},
{CompanyNameJOIN:"Kia Motors",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"Kii Corporation",SubCategory:"",Category:""},
{CompanyNameJOIN:"Kinestral Technologies",SubCategory:"",Category:""},
{CompanyNameJOIN:"Kinzan.com",SubCategory:"",Category:""},
{CompanyNameJOIN:"Konfio",SubCategory:"",Category:""},
{CompanyNameJOIN:"Koolicar",SubCategory:"",Category:""},
{CompanyNameJOIN:"Kuaidi Dache",SubCategory:"",Category:""},
{CompanyNameJOIN:"Kudo",SubCategory:"",Category:""},
{CompanyNameJOIN:"Kyash",SubCategory:"",Category:""},
{CompanyNameJOIN:"Kyriba",SubCategory:"",Category:""},
{CompanyNameJOIN:"Kyriba Japan",SubCategory:"",Category:""},
{CompanyNameJOIN:"Leo",SubCategory:"",Category:""},
{CompanyNameJOIN:"LifeRobotics",SubCategory:"",Category:""},
{CompanyNameJOIN:"Liftit",SubCategory:"",Category:""},
{CompanyNameJOIN:"Lime",SubCategory:"Mobility Provider",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"Lincoln Motor Company",SubCategory:"Car Manufacturer",Category:"Others"},
{CompanyNameJOIN:"Li-Tec Battery",SubCategory:"",Category:""},
{CompanyNameJOIN:"Livio Radio",SubCategory:"",Category:""},
{CompanyNameJOIN:"Lizardtech",SubCategory:"",Category:""},
{CompanyNameJOIN:"LoiLo",SubCategory:"",Category:""},
{CompanyNameJOIN:"Lotus Cars",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"Luxe",SubCategory:"",Category:""},
{CompanyNameJOIN:"LUXI Co. Ltd.",SubCategory:"",Category:""},
{CompanyNameJOIN:"LuxN",SubCategory:"",Category:""},
{CompanyNameJOIN:"Lytx",SubCategory:"",Category:""},
{CompanyNameJOIN:"macaron TAXI (KST Intelligence)",SubCategory:"",Category:""},
{CompanyNameJOIN:"Macro",SubCategory:"",Category:""},
{CompanyNameJOIN:"MainVest",SubCategory:"",Category:""},
{CompanyNameJOIN:"MakeMusic, Inc.",SubCategory:"",Category:""},
{CompanyNameJOIN:"MakinaRocks",SubCategory:"",Category:""},
{CompanyNameJOIN:"mana.bo Inc.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Manganese Bronze Holdings PLC",SubCategory:"",Category:""},
{CompanyNameJOIN:"Manthey-Racing",SubCategory:"",Category:""},
{CompanyNameJOIN:"Markforged",SubCategory:"",Category:""},
{CompanyNameJOIN:"Maxwell Technologies",SubCategory:"",Category:""},
{CompanyNameJOIN:"MDGo",SubCategory:"",Category:""},
{CompanyNameJOIN:"Medcom Sp. z o.o.",SubCategory:"",Category:""},
{CompanyNameJOIN:"MELCO Hydronics & IT Cooling S.p.A.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Messung Group",SubCategory:"",Category:""},
{CompanyNameJOIN:"Metawave",SubCategory:"",Category:""},
{CompanyNameJOIN:"MICIN Inc.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Mighty AI",SubCategory:"",Category:""},
{CompanyNameJOIN:"Mind Palette",SubCategory:"",Category:""},
{CompanyNameJOIN:"MineSense Technologies",SubCategory:"",Category:""},
{CompanyNameJOIN:"Mister Auto",SubCategory:"",Category:""},
{CompanyNameJOIN:"Mitsubishi Electric Klimat Transportation Systems S.p.A",SubCategory:"",Category:""},
{CompanyNameJOIN:"Mitsubishi Motors",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"Mobileum",SubCategory:"",Category:""},
{CompanyNameJOIN:"mobilityX",SubCategory:"",Category:""},
{CompanyNameJOIN:"Moca",SubCategory:"",Category:""},
{CompanyNameJOIN:"Modulated Imaging",SubCategory:"",Category:""},
{CompanyNameJOIN:"Moixa Technology",SubCategory:"",Category:""},
{CompanyNameJOIN:"Momentum Dynamics Corp",SubCategory:"",Category:""},
{CompanyNameJOIN:"Money Forward",SubCategory:"",Category:""},
{CompanyNameJOIN:"Moneytree",SubCategory:"",Category:""},
{CompanyNameJOIN:"Monstar Lab",SubCategory:"",Category:""},
{CompanyNameJOIN:"Motivate",SubCategory:"",Category:""},
{CompanyNameJOIN:"Muse & Co",SubCategory:"",Category:""},
{CompanyNameJOIN:"Nanotech Partners",SubCategory:"",Category:""},
{CompanyNameJOIN:"Nema Labs",SubCategory:"",Category:""},
{CompanyNameJOIN:"NEO RETRO",SubCategory:"",Category:""},
{CompanyNameJOIN:"NeoPhotonics",SubCategory:"",Category:""},
{CompanyNameJOIN:"NetLogic Microsystems",SubCategory:"",Category:""},
{CompanyNameJOIN:"NeurogesX",SubCategory:"",Category:""},
{CompanyNameJOIN:"Nexu",SubCategory:"",Category:""},
{CompanyNameJOIN:"Ninja Van",SubCategory:"",Category:""},
{CompanyNameJOIN:"Nubimetrics",SubCategory:"",Category:""},
{CompanyNameJOIN:"Nuvve",SubCategory:"",Category:""},
{CompanyNameJOIN:"NxtPhase",SubCategory:"",Category:""},
{CompanyNameJOIN:"NxtWave Communications",SubCategory:"",Category:""},
{CompanyNameJOIN:"ObjectVideo",SubCategory:"",Category:""},
{CompanyNameJOIN:"Oceans Inc.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Ogwugo",SubCategory:"",Category:""},
{CompanyNameJOIN:"OLAM International",SubCategory:"",Category:""},
{CompanyNameJOIN:"OmniSonics Medical Technologies",SubCategory:"",Category:""},
{CompanyNameJOIN:"Opel Group",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"Opel Special Vehicles",SubCategory:"",Category:""},
{CompanyNameJOIN:"Open Harbor",SubCategory:"",Category:""},
{CompanyNameJOIN:"Orocobre",SubCategory:"",Category:""},
{CompanyNameJOIN:"Otto",SubCategory:"",Category:""},
{CompanyNameJOIN:"OVO Energy",SubCategory:"",Category:""},
{CompanyNameJOIN:"OYO",SubCategory:"",Category:""},
{CompanyNameJOIN:"Panacea Pharmaceuticals",SubCategory:"",Category:""},
{CompanyNameJOIN:"PayByPhone Technologies",SubCategory:"parking",Category:"Connected"},
{CompanyNameJOIN:"Peloton Technology",SubCategory:"",Category:""},
{CompanyNameJOIN:"Peninsula Pharmaceuticals",SubCategory:"",Category:""},
{CompanyNameJOIN:"Perbix",SubCategory:"",Category:""},
{CompanyNameJOIN:"Percepto",SubCategory:"",Category:""},
{CompanyNameJOIN:"Plaid inc",SubCategory:"",Category:""},
{CompanyNameJOIN:"Platypus Technology",SubCategory:"",Category:""},
{CompanyNameJOIN:"PointGrab",SubCategory:"",Category:""},
{CompanyNameJOIN:"PontaMedia",SubCategory:"",Category:""},
{CompanyNameJOIN:"Porsche",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"Port Medical",SubCategory:"",Category:""},
{CompanyNameJOIN:"Power Vehicle Innovation",SubCategory:"",Category:""},
{CompanyNameJOIN:"PowerCell Sweden",SubCategory:"",Category:""},
{CompanyNameJOIN:"Powerex",SubCategory:"",Category:""},
{CompanyNameJOIN:"Powerhive",SubCategory:"",Category:""},
{CompanyNameJOIN:"PowerShare",SubCategory:"",Category:""},
{CompanyNameJOIN:"Prism Entertainment",SubCategory:"",Category:""},
{CompanyNameJOIN:"Producteca",SubCategory:"",Category:""},
{CompanyNameJOIN:"Promethera Biosciences",SubCategory:"",Category:""},
{CompanyNameJOIN:"Prophesee",SubCategory:"",Category:""},
{CompanyNameJOIN:"proteanTecs",SubCategory:"",Category:""},
{CompanyNameJOIN:"PTV Group",SubCategory:"",Category:""},
{CompanyNameJOIN:"Pulsar Technology",SubCategory:"",Category:""},
{CompanyNameJOIN:"Quake Technologies",SubCategory:"",Category:""},
{CompanyNameJOIN:"Quantum Biosystems",SubCategory:"",Category:""},
{CompanyNameJOIN:"Quantum Signal",SubCategory:"",Category:""},
{CompanyNameJOIN:"R3",SubCategory:"",Category:""},
{CompanyNameJOIN:"Rapid Motor Vehicle Company",SubCategory:"",Category:""},
{CompanyNameJOIN:"RareJob Inc.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Raven Biotechnologies",SubCategory:"",Category:""},
{CompanyNameJOIN:"Recogni",SubCategory:"",Category:""},
{CompanyNameJOIN:"REE",SubCategory:"",Category:""},
{CompanyNameJOIN:"REGiMMUNE Corporation",SubCategory:"",Category:""},
{CompanyNameJOIN:"Reliance Jio Infocomm Limited",SubCategory:"",Category:""},
{CompanyNameJOIN:"Reliance Motor Car Company",SubCategory:"",Category:""},
{CompanyNameJOIN:"Renewable Energy Trust Capital",SubCategory:"",Category:""},
{CompanyNameJOIN:"Respiro",SubCategory:"",Category:""},
{CompanyNameJOIN:"Retty",SubCategory:"",Category:""},
{CompanyNameJOIN:"RidePal",SubCategory:"",Category:""},
{CompanyNameJOIN:"Rioport",SubCategory:"",Category:""},
{CompanyNameJOIN:"Ritase",SubCategory:"",Category:""},
{CompanyNameJOIN:"Riviera Tool LLC",SubCategory:"",Category:""},
{CompanyNameJOIN:"Rover",SubCategory:"",Category:""},
{CompanyNameJOIN:"Scania",SubCategory:"Truck Manufacturer",Category:"Others"},
{CompanyNameJOIN:"Seak",SubCategory:"",Category:""},
{CompanyNameJOIN:"Security Bank Corporation",SubCategory:"",Category:""},
{CompanyNameJOIN:"Serenex",SubCategory:"",Category:""},
{CompanyNameJOIN:"Setsuyo Astec Corp.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Seven Seas Technologies Group",SubCategory:"",Category:""},
{CompanyNameJOIN:"Shenyang Brilliance JinBei Automobile",SubCategory:"",Category:""},
{CompanyNameJOIN:"Sidecar Technologies",SubCategory:"",Category:""},
{CompanyNameJOIN:"Silicon Wave",SubCategory:"",Category:""},
{CompanyNameJOIN:"SiRF Technology",SubCategory:"",Category:""},
{CompanyNameJOIN:"sitateru",SubCategory:"",Category:""},
{CompanyNameJOIN:"Skybox Security",SubCategory:"",Category:""},
{CompanyNameJOIN:"SMARTCAMP Co.,Ltd.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Snapeee",SubCategory:"",Category:""},
{CompanyNameJOIN:"Softbank",SubCategory:"",Category:""},
{CompanyNameJOIN:"SolarCity",SubCategory:"",Category:""},
{CompanyNameJOIN:"Solve MIT",SubCategory:"",Category:"Others"},
{CompanyNameJOIN:"Sonexa Therapeutics",SubCategory:"",Category:""},
{CompanyNameJOIN:"Sonus Networks",SubCategory:"",Category:""},
{CompanyNameJOIN:"Spare",SubCategory:"",Category:""},
{CompanyNameJOIN:"Splyt",SubCategory:"",Category:""},
{CompanyNameJOIN:"StradVision",SubCategory:"",Category:""},
{CompanyNameJOIN:"Summit Power International Ltd.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Sunhill Technologies",SubCategory:"",Category:""},
{CompanyNameJOIN:"Swiftly",SubCategory:"",Category:""},
{CompanyNameJOIN:"Swipe Labs",SubCategory:"",Category:""},
{CompanyNameJOIN:"Swit",SubCategory:"",Category:""},
{CompanyNameJOIN:"Sylpheo",SubCategory:"Software development",Category:"Others"},
{CompanyNameJOIN:"Symphony Communication Services",SubCategory:"",Category:""},
{CompanyNameJOIN:"Teknovus",SubCategory:"",Category:""},
{CompanyNameJOIN:"TeraLogic",SubCategory:"",Category:""},
{CompanyNameJOIN:"Terrafugia",SubCategory:"",Category:""},
{CompanyNameJOIN:"Terra-Gen Power",SubCategory:"",Category:""},
{CompanyNameJOIN:"The Markup",SubCategory:"",Category:""},
{CompanyNameJOIN:"The Mobility House",SubCategory:"",Category:""},
{CompanyNameJOIN:"ticketstreet",SubCategory:"",Category:""},
{CompanyNameJOIN:"Tokyo Otaku Mode",SubCategory:"",Category:""},
{CompanyNameJOIN:"TradeBeam",SubCategory:"",Category:""},
{CompanyNameJOIN:"TradeCard",SubCategory:"",Category:""},
{CompanyNameJOIN:"Tragara",SubCategory:"",Category:""},
{CompanyNameJOIN:"TranSiC",SubCategory:"",Category:""},
{CompanyNameJOIN:"Trillium Secure",SubCategory:"",Category:""},
{CompanyNameJOIN:"TRINAMIC Motion Control",SubCategory:"",Category:""},
{CompanyNameJOIN:"TVS Logistics Services",SubCategory:"",Category:""},
{CompanyNameJOIN:"Uber China",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
{CompanyNameJOIN:"ubitricity",SubCategory:"",Category:""},
{CompanyNameJOIN:"UDcast",SubCategory:"",Category:""},
{CompanyNameJOIN:"United States Artists",SubCategory:"",Category:""},
{CompanyNameJOIN:"Univision Communications",SubCategory:"",Category:""},
{CompanyNameJOIN:"UVeye",SubCategory:"",Category:""},
{CompanyNameJOIN:"Uzabase",SubCategory:"",Category:""},
{CompanyNameJOIN:"Vaprema",SubCategory:"",Category:""},
{CompanyNameJOIN:"Varjo",SubCategory:"",Category:""},
{CompanyNameJOIN:"VAYAVISION",SubCategory:"",Category:""},
{CompanyNameJOIN:"VeriSign",SubCategory:"",Category:""},
{CompanyNameJOIN:"Vincotech Holdings S.a.r.l.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Volvo Cars Group",SubCategory:"OEM",Category:"Others"},
{CompanyNameJOIN:"VTXRM",SubCategory:"",Category:""},
{CompanyNameJOIN:"Waypoint Leasing Services",SubCategory:"",Category:""},
{CompanyNameJOIN:"Wealthnavi",SubCategory:"",Category:""},
{CompanyNameJOIN:"WHILL",SubCategory:"",Category:""},
{CompanyNameJOIN:"Whyteboard",SubCategory:"",Category:""},
{CompanyNameJOIN:"WirelessCar",SubCategory:"",Category:""},
{CompanyNameJOIN:"Xchange Leasing",SubCategory:"",Category:""},
{CompanyNameJOIN:"xenodata lab",SubCategory:"",Category:""},
{CompanyNameJOIN:"Xiaomi",SubCategory:"Electronics",Category:"Connected"},
{CompanyNameJOIN:"Xtra, Inc.",SubCategory:"",Category:""},
{CompanyNameJOIN:"Yeong Guan Energy",SubCategory:"",Category:""},
{CompanyNameJOIN:"YesGraph",SubCategory:"",Category:""},
{CompanyNameJOIN:"Zipline",SubCategory:"",Category:""},
{CompanyNameJOIN:"Zola Electric",SubCategory:"",Category:""},
{CompanyNameJOIN:"Zolvers",SubCategory:"",Category:""},
{CompanyNameJOIN:"ZRRO",SubCategory:"",Category:""}
      ];
      var categoriesTableData = [];
      for (var i = 0, len = CategoriesList.length; i < len; i++) {
        categoriesTableData.push({
          "company_name_JOIN": CategoriesList[i].CompanyNameJOIN,
          "subcategory": CategoriesList[i].SubCategory,
          "category": CategoriesList[i].Category
        });
      }
      table.appendRows(categoriesTableData);
    doneCallback();
  }

  };

  tableau.registerConnector(myConnector);

  $(document).ready(function() {
    $("#submitButton").click(function() {
      tableau.connectionName = "CrunchBase Feed";
      tableau.submit();
    });
  });
})();
