(function() {

  /***************************************************************************************************/
  /**************************** PREPARATION CODE *****************************************************/
  /***************************************************************************************************/

  // Browse companies listed as parameter by UUID & Name and get all investments & acquisitions from CrunchBase APIs
  function getInvestmentsAcquisitionsByCompanies(p_companyList, p_table) {
    // Iterate for as many companies as listed above
    for (var i = 0, len = p_companyList.length; i < len; i++) {
      var Sector = p_companyList[i].Sector;
      var Group = p_companyList[i].Group;
      var Company = p_companyList[i].Company;
      var Investor = p_companyList[i].Investor;
      var UUID = p_companyList[i].UUID;

      // GET INVESTMENTS DATA
      var PageNo = 1;
      var Next_page_url = "init";
      do {
        $.ajax({
          url: "https://api.crunchbase.com/v3.1/organizations/" + UUID + "/investments?user_key=9df45b533650fb1b95e83357b5da2db3&items_per_page=250&page=" + PageNo, // browse the list of investments
          async: false,
          indexValue: {
            paramSector: Sector,
            paramGroup: Group,
            paramCompany: Company,
            paramInvestor: Investor
          }, // to get Investor value from out of the ajaxCall
          success: function(response) {
            var investmentsJSON = response.data.items;
            var investmentTableData = [];
            for (var iI = 0, leniI = investmentsJSON.length; iI < leniI; iI++) {
              var Announced_Date = investmentsJSON[iI].properties.announced_on;
              var MoneyRaised = investmentsJSON[iI].relationships.funding_round.properties.money_raised_usd;
              if (MoneyRaised == null) MoneyRaised = 0;
              var FundingRoundType = investmentsJSON[iI].relationships.funding_round.type;
              var FundingType = investmentsJSON[iI].relationships.funding_round.properties.funding_type;
              var Series = investmentsJSON[iI].relationships.funding_round.properties.series;
              if (Series == null) Series = "";
              var FinalFundingType = FundingRoundType + " " + FundingType + " " + Series;
              var FundedCompany = investmentsJSON[iI].relationships.funding_round.relationships.funded_organization.properties.name;
              var FundedCompanyUUID = investmentsJSON[iI].relationships.funding_round.relationships.funded_organization.uuid;
              var ShortDescription = investmentsJSON[iI].relationships.funding_round.relationships.funded_organization.properties.short_description;
              var Description = investmentsJSON[iI].relationships.funding_round.relationships.funded_organization.properties.description;

              investmentTableData.push({
                "sector": this.indexValue.paramSector,
                "group": this.indexValue.paramGroup,
                "company": this.indexValue.paramCompany,
                "investor": this.indexValue.paramInvestor, // to get Investor value from out of the ajaxCall
                "transaction_type": "Investment",
                "funding_type": FinalFundingType,
                "money_raised": MoneyRaised,
                "announced_date": Announced_Date,
                "company_name_JOIN": FundedCompany,
                "target_company": FundedCompany,
                "short_description": ShortDescription,
                "description": Description
              });
            }
            p_table.appendRows(investmentTableData);
            Next_page_url = response.data.paging.next_page_url;
          }
        });
        PageNo++;
      }
      while (Next_page_url != null)

      // GET ACQUISITIONS DATA
      var PageNo2 = 1;
      var Next_page_url2 = "init";
      do {
        $.ajax({
          url: "https://api.crunchbase.com/v3.1/organizations/" + UUID + "/acquisitions?user_key=9df45b533650fb1b95e83357b5da2db3&items_per_page=250&page=" + PageNo2, // browse the list of acquisitions
          async: false,
          indexValue: {
            paramSector: Sector,
            paramGroup: Group,
            paramCompany: Company,
            paramInvestor: Investor
          }, // to get Investor value from out of the ajaxCall
          success: function(response2) {
            var acquisitionsJSON = response2.data.items;
            var acquisitionTableData = [];
            for (var iA = 0, leniA = acquisitionsJSON.length; iA < leniA; iA++) {
              var Announced_Date = acquisitionsJSON[iA].properties.announced_on;
              var MoneyRaised = acquisitionsJSON[iA].properties.price_usd;
              if (MoneyRaised == null) MoneyRaised = 0;
              var AcquiredCompany = acquisitionsJSON[iA].relationships.acquiree.properties.name;
              var ShortDescription = acquisitionsJSON[iA].relationships.acquiree.properties.short_description;
              var Description = acquisitionsJSON[iA].relationships.acquiree.properties.description;

              acquisitionTableData.push({
                "sector": this.indexValue.paramSector,
                "group": this.indexValue.paramGroup,
                "company": this.indexValue.paramCompany,
                "investor": this.indexValue.paramInvestor, // to get Investor value from out of the ajaxCall
                "transaction_type": "Acquisition",
                "funding_type": "",
                "money_raised": MoneyRaised,
                "announced_date": Announced_Date,
                "company_name_JOIN": AcquiredCompany,
                "target_company": AcquiredCompany,
                "short_description": ShortDescription,
                "description": Description
              });
            }
            p_table.appendRows(acquisitionTableData);
            Next_page_url2 = response2.data.paging.next_page_url;
          }
        });
        PageNo2++;
      } while (Next_page_url2 != null)
    }
  }

  // Inserts HARDCODED partnerships into the same table as Investments/Acquisitions
  function insertPartnerships(p_table) {
    var PartnershipsList = [
      {Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"AmazonCS",Company1:"Amazon"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Supplier",CompanyNameJOIN:"Here Technologies",Company1:"Here Technologies"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"what3words",Company1:"what3words"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Supplier",CompanyNameJOIN:"AT&T",Company1:"AT&T"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"ChargePoint",Company1:"ChargePoint"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"QualcommCEC",Company1:"Qualcomm"},
{Sector:"OEM",Group:"KIA",Company:"Kia",Investor:"Kia",TransactionType:"Partnership",CompanyNameJOIN:"Vodafone",Company1:"Vodafone"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"Vodafone",Company1:"Vodafone"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Walmart",Company1:"Walmart"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"Otonomo",Company1:"Otonomo"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"Deepglint",Company1:"Deepglint"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Soundhound Inc.",Company1:"Soundhound Inc."},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"Soundhound Inc.",Company1:"Soundhound Inc."},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Shell",Company1:"Shell"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"ParkMobile",Company1:"ParkMobile"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"DaimlerCS",Company1:"Daimler"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Aurora",Company1:"Aurora"},
{Sector:"OEM",Group:"Byton",Company:"Byton",Investor:"Byton",TransactionType:"Partnership",CompanyNameJOIN:"Aurora",Company1:"Aurora"},
{Sector:"OEM",Group:"KIA",Company:"Kia",Investor:"Kia",TransactionType:"Partnership",CompanyNameJOIN:"Vulog",Company1:"Vulog"},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"Vulog",Company1:"Vulog"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Cleenup",Company1:"Cleenup"},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"HuaweiCEC",Company1:"Huawei"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Uber",Company1:"Uber"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Uber",Company1:"Uber"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"Bosch",Company1:"Bosch"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"Uber",Company1:"Uber"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Aurora",Company1:"Aurora"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Continental",Company1:"Continental"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Delphi",Company1:"Delphi"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Intel",Company1:"Intel"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Lyft",Company1:"Lyft"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Mobileye",Company1:"Mobileye"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Microsoft",Company1:"Microsoft"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Mobileye",Company1:"Mobileye"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Google",Company1:"Google"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Google",Company1:"Google"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Microsoft",Company1:"Microsoft"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"JLR",Company1:"JLR"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Alibaba",Company1:"Alibaba"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Alibaba",Company1:"Alibaba"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Alibaba",Company1:"Alibaba"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"IBM",Company1:"IBM"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"IBM",Company1:"IBM"},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"IBM",Company1:"IBM"},
{Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Partnership",CompanyNameJOIN:"Valeo",Company1:"Valeo"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"HuaweiCEC",Company1:"Huawei"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"Vodafone",Company1:"Vodafone"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"Siemens",Company1:"Siemens"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"QualcommAE",Company1:"Qualcomm"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Didi Chuxing",Company1:"Didi Chuxing"},
{Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"YandexN",Company1:"Yandex"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"YandexN",Company1:"Yandex"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Tomtom",Company1:"Tomtom"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Microsoft",Company1:"Microsoft"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"NASA",Company1:"NASA"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"DeNA",Company1:"DeNA"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Didi Chuxing",Company1:"Didi Chuxing"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"HuaweiS",Company1:"Huawei"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Microsoft",Company1:"Microsoft"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Ford",Company1:"Ford"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"BMW",Company1:"BMW"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"ChargePoint",Company1:"ChargePoint"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Engie",Company1:"Engie"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Enel",Company1:"Enel"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"EVgo",Company1:"EVgo"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"EVgo",Company1:"EVgo"},
{Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",TransactionType:"Partnership",CompanyNameJOIN:"Panasonic",Company1:"Panasonic"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Panasonic",Company1:"Panasonic"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"CATL",Company1:"CATL"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Samsung SDI",Company1:"Samsung SDI"},
{Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda",TransactionType:"Partnership",CompanyNameJOIN:"CATL",Company1:"CATL"},
{Sector:"OEM",Group:"VAG",Company:"Porsche",Investor:"Porsche",TransactionType:"Partnership",CompanyNameJOIN:"Chargetrip",Company1:"Chargetrip"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Disney",Company1:"Disney"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"INRIX",Company1:"INRIX"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Nvidia",Company1:"Nvidia"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"AmazonS",Company1:"Amazon"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Pizza Hut",Company1:"Pizza Hut"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Dominos",Company1:"Dominos"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Supplier",CompanyNameJOIN:"Zenuity",Company1:"Zenuity"},
{Sector:"OEM",Group:"Alliance RNM",Company:"RNM",Investor:"RNM",TransactionType:"Partnership",CompanyNameJOIN:"Waymo",Company1:"Waymo"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Baidu",Company1:"Baidu"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"AmazonS",Company1:"Amazon"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Luminar",Company1:"Luminar"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"Luminar",Company1:"Luminar"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"HuaweiADS",Company1:"Huawei"},
{Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",TransactionType:"Partnership",CompanyNameJOIN:"Airbus",Company1:"Airbus"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"YandexADS",Company1:"Yandex"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Garmin",Company1:"Garmin"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Lidl",Company1:"Lidl"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Kaufland",Company1:"Kaufland"},
{Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Partnership",CompanyNameJOIN:"Vulog",Company1:"Vulog"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"DaimlerADS",Company1:"Daimler"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"BMW",Company:"Mini",Investor:"Mini",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Spotify",Company1:"Spotify"},
{Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"BMW",Company:"Mini",Investor:"Mini",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"JLR",TransactionType:"Partnership",CompanyNameJOIN:"TuneIn",Company1:"TuneIn"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Audible",Company1:"Audible"},
{Sector:"OEM",Group:"FCA",Company:"FCA",Investor:"FCA",TransactionType:"Partnership",CompanyNameJOIN:"Xevo",Company1:"Xevo"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"Xevo",Company1:"Xevo"},
{Sector:"OEM",Group:"GM",Company:"GM",Investor:"GM",TransactionType:"Partnership",CompanyNameJOIN:"Xevo",Company1:"Xevo"},
{Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai",TransactionType:"Partnership",CompanyNameJOIN:"Wind River",Company1:"Wind River"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Tencent",Company1:"Tencent"},
{Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Partnership",CompanyNameJOIN:"Baidu",Company1:"Baidu"},
{Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota",TransactionType:"Partnership",CompanyNameJOIN:"BYD",Company1:"BYD"}
    ];

    var partnershipsTableData = [];
    for (var i = 0, len = PartnershipsList.length; i < len; i++) {
      partnershipsTableData.push({
        "sector": PartnershipsList[i].Sector,
        "group": PartnershipsList[i].Group,
        "company": PartnershipsList[i].Company,
        "investor": PartnershipsList[i].Investor,
        "transaction_type": PartnershipsList[i].TransactionType,
        "funding_type": "",
        "money_raised": "",
        "announced_date": "",
        "company_name_JOIN": PartnershipsList[i].CompanyNameJOIN,
        "target_company": PartnershipsList[i].Company1,
        "short_description": "",
        "description": ""
      });
    }
    p_table.appendRows(partnershipsTableData);
  }

  // Inserts HARDCODED subsidiaries into the same table as Investments/Acquisitions
  function insertSubsidiaries(p_table) {
    var SubsidiariesList = [
      {Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Subsidiary",CompanyNameJOIN:"ShareNow",AnnouncedDate:"01/01/2019"},
      {Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Subsidiary",CompanyNameJOIN:"ShareNow",AnnouncedDate:"01/01/2019"},
      {Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Subsidiary",CompanyNameJOIN:"Free2Move",AnnouncedDate:"00/01/1900"},
      {Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Subsidiary",CompanyNameJOIN:"Free2Move Paris",AnnouncedDate:"00/01/1900"},
      {Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA",TransactionType:"Subsidiary",CompanyNameJOIN:"eMov",AnnouncedDate:"00/01/1900"},
      {Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen",TransactionType:"Subsidiary",CompanyNameJOIN:"WeShare",AnnouncedDate:"00/01/1900"},
      {Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",TransactionType:"Subsidiary",CompanyNameJOIN:"Hive",AnnouncedDate:"00/01/1900"},
      {Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",TransactionType:"Subsidiary",CompanyNameJOIN:"Hive",AnnouncedDate:"00/01/1900"}
    ];

    var subsidiariesTableData = [];
    for (var i = 0, len = SubsidiariesList.length; i < len; i++) {
      subsidiariesTableData.push({
        "sector": SubsidiariesList[i].Sector,
        "group": SubsidiariesList[i].Group,
        "company": SubsidiariesList[i].Company,
        "investor": SubsidiariesList[i].Investor,
        "transaction_type": SubsidiariesList[i].TransactionType,
        "funding_type": "",
        "money_raised": "",
        "announced_date": SubsidiariesList[i].Date,
        "company_name_JOIN": SubsidiariesList[i].CompanyNameJOIN,
        "target_company": SubsidiariesList[i].CompanyNameJOIN,
        "short_description": "",
        "description": ""
      });
    }
  }

  /***************************************************************************************************/
  /******************************** RUNNING CODE *****************************************************/
  /***************************************************************************************************/

  var myConnector = tableau.makeConnector();

  // When you create multiple table schemas, the WDC API calls the getData function once for each schema.
  myConnector.getSchema = function(schemaCallback) {

    // Transactions : Investments & Acquisitions
    var Transactions_cols = [
    {
      id: "sector",
      alias: "Sector",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "group",
      alias: "Group",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "company",
      alias: "Company",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "investor",
      alias: "Investor",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "transaction_type",
      alias: "Transaction Type",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "funding_type",
      alias: "Funding Type",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "money_raised",
      alias: "Money Raised",
      dataType: tableau.dataTypeEnum.int
    }, {
      id: "announced_date",
      alias: "Announced Date",
      dataType: tableau.dataTypeEnum.date
    }, {
      id: "company_name_JOIN",
      alias: "Company Name JOIN",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "target_company",
      alias: "Target Company",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "short_description",
      alias: "Short Description",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "description",
      alias: "Description",
      dataType: tableau.dataTypeEnum.string
    }
    ];
    var Transactions_Schema = {
      id: "Transactions", // table.tableInfo.id
      alias: "Transactions",
      columns: Transactions_cols
    };

    // Categories : Companies and their categories, coming from StartUp Flow
    var Categories_cols = [
    {
      id: "company_name_JOIN",
      alias: "Company Name JOIN",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "subcategory",
      alias: "Sub Category",
      dataType: tableau.dataTypeEnum.string
    }, {
      id: "category",
      alias: "Category",
      dataType: tableau.dataTypeEnum.string
    }
    ];
    var Categories_Schema = {
      id: "Categories", // table.tableInfo.id
      alias: "Categories",
      columns: Categories_cols
    };

    // It's only when several schemas are passed to this function that the getData function is called several times
    schemaCallback([Transactions_Schema,Categories_Schema]);
  };

  // When you create multiple table schemas, the WDC API calls the getData function once for each schema.
  // As a result, you need a way to change the call to the API for each table. The easiest way to do this is to use the table.tableInfo.id value that we set in the table schemas.
  myConnector.getData = function(table, doneCallback) {

    if (table.tableInfo.id == "Transactions") {
      var CompaniesList = [
        {Sector:"OEM",Group:"Alliance RNM",Company:"Alliance",Investor:"Renault Nissan Mitsubishi",UUID:"96fa22e600c4656428f64b2066e4021d"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Alliance",Investor:"Alliance Ventures",UUID:"bded51bc070240d5ba0e6771d44c5146"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi Motors",UUID:"fe8f7d6b2f90470223b5d7f18ca63a51"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi Electric",UUID:"2e1e8791e661a34d9a78bcabfdd1825f"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi UFJ Financial Group",UUID:"d4974159c3765f1b93c50cc0c187423b"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi Corporation",UUID:"b8d382916018dd9083ec0723756f2949"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi UFJ Capital",UUID:"d300b7548f03f143a08309c355f716ba"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Bank Of Tokyo - Mitsubishi UFJ",UUID:"453bb5c7da0798805c29a960edbb0676"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Mitsubishi",Investor:"Mitsubishi International Corporation (MIC)",UUID:"176c343305f21c86a44393949ae65681"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Nissan",Investor:"Nissan Motor Corporation",UUID:"718eb41ba3098cd45e019958ac876ee5"},
        {Sector:"OEM",Group:"Alliance RNM",Company:"Renault",Investor:"Renault",UUID:"96ff3fd230b3249437059d861033a53e"},
        {Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW",UUID:"b462608d8bf493f14f68e41ee10f0df2"},
        {Sector:"OEM",Group:"BMW",Company:"BMW",Investor:"BMW i Ventures",UUID:"0e35699837f1d2b1b6eb2b62cf418b3e"},
        {Sector:"OEM",Group:"Daimler",Company:"Daimler",Investor:"Daimler",UUID:"5d6ed201f03268afb4227e7c68129485"},
        {Sector:"Mobility",Group:"Didi Chuxing",Company:"Didi",Investor:"Didi Chuxing",UUID:"eab915a8f41464e05138c5f341596a5b"},
        {Sector:"OEM",Group:"FCA",Company:"Fiat",Investor:"FIAT S.p.A",UUID:"e7b7f5416f80e13f335f3b0932884c4c"},
        {Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford Motor Company",UUID:"9249e8b6409aa80c1a1e29ae21b1db47"},
        {Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford Foundation",UUID:"0ee8cd71bfd9bf6bfb96a38012b1e001"},
        {Sector:"OEM",Group:"Ford",Company:"Ford",Investor:"Ford Smart Mobility",UUID:"e5a7c1b5702f9efe3e3ebacc0e5e654c"},
        {Sector:"OEM",Group:"Geely",Company:"Geely",Investor:"Zhejiang Geely Holding Group",UUID:"cbcae3286143e6a215efd8b736ca9fff"},
        {Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo Group Venture Capital",UUID:"9a59d1e9d183001585270a39d01a9bfc"},
        {Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo Cars Group",UUID:"1894c8007d82904566067461508339da"},
        {Sector:"OEM",Group:"Geely",Company:"Volvo",Investor:"Volvo Cars Tech Fund",UUID:"86d2a05fdff04a4cbccb9f467e5ecc6e"},
        {Sector:"OEM",Group:"GM",Company:"GM",Investor:"General Motors Investment Management",UUID:"a1d14b6f137ebeaa847a8ba7ad65b4ea"},
        {Sector:"OEM",Group:"GM",Company:"GM",Investor:"General Motors",UUID:"5087a04780c54aa3dfdf30dd8ac88b5e"},
        {Sector:"OEM",Group:"GM",Company:"GM",Investor:"General Motors Ventures",UUID:"759be29a69e1615d373f8f8d8f020591"},
        {Sector:"Mobility",Group:"Grab",Company:"Grab",Investor:"Grab",UUID:"a76824768a83dbcf73dc41a841ef850e"},
        {Sector:"OEM",Group:"Honda",Company:"Honda",Investor:"Honda Motor",UUID:"0017e370d941822e83bc538beaab28da"},
        {Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai Motor Company",UUID:"271e1bf5086adbb89806b76a591b864e"},
        {Sector:"OEM",Group:"Hyundai",Company:"Hyundai",Investor:"Hyundai Venture Investment Corporation",UUID:"994661433b9eb9fc9283116b7b32af5a"},
        {Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"Jaguar Land Rover",UUID:"4b6fd457050953c1db591f694f5ef77b"},
        {Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"Jaguar Ventures",UUID:"75213e229421b3687e50a36e9ddf1cec"},
        {Sector:"OEM",Group:"JLR",Company:"JLR",Investor:"Jaguar Land Rover’s venture capital fund",UUID:"ec11c33226e64c7db12a92b9305cf0dd"},
        {Sector:"OEM",Group:"KIA",Company:"Kia",Investor:"Kia Motors",UUID:"396458db49b8888dfba24953402d3d66"},
        {Sector:"Mobility",Group:"Lyft",Company:"Lyft",Investor:"Lyft",UUID:"33a97e70f137e90f8d68950a043ee09f"},
        {Sector:"OEM",Group:"PSA",Company:"PSA",Investor:"PSA Group",UUID:"7c01753993a20640220b5b05a855210a"},
        {Sector:"OEM",Group:"PSA",Company:"Peugeot",Investor:"Peugeot SA",UUID:"ee1dec4f08abb10cd37aa27ef162d215"},
        {Sector:"OEM",Group:"Tesla",Company:"Tesla",Investor:"Tesla",UUID:"a367b036595254357541ad7ee8869e24"},
        {Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota Motor Corporation",UUID:"12b90373ab49a56a4b4ec7b3e9236faf"},
        {Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota Tsusho",UUID:"4ecb67dc639df5b6cd57da212250cebc"},
        {Sector:"OEM",Group:"Toyota",Company:"Toyota",Investor:"Toyota AI Ventures",UUID:"4419828e7e06f10e323c4e985821dafd"},
        {Sector:"Mobility",Group:"Uber",Company:"Uber",Investor:"Uber",UUID:"1eb371093b9301a9177ffee2cb1bfcdc"},
        {Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen group",UUID:"8a2b18d24cfbac1708b207b01d092e2a"},
        {Sector:"OEM",Group:"VAG",Company:"Audi",Investor:"Audi",UUID:"81a1ceaa081ffe4ffbb4ca4cbc8293a8"},
        {Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen We",UUID:"a31b34c32f6543789fb20993d74b4dad"},
        {Sector:"OEM",Group:"VAG",Company:"Volkswagen",Investor:"Volkswagen Financial Services",UUID:"5449c78f0a2a24b1c2f1414ec2e27917"},
        {Sector:"OEM",Group:"VAG",Company:"Porsche",Investor:"Porsche",UUID:"68255d6d16144c7c1a0b3d3998c1d2c2"},
        {Sector:"OEM",Group:"VAG",Company:"Porsche",Investor:"Porsche Automobil Holding",UUID:"8ea457a172805992c020e741fef4a8dc"},
        {Sector:"OEM",Group:"VAG",Company:"Seat",Investor:"Seat",UUID:"fdf2b2f2241533a054ad3b9755b84f33"},
        {Sector:"OEM",Group:"VAG",Company:"Škoda",Investor:"Škoda Auto a.s ",UUID:"7c71810f27514e8c95d7e2fae0b96178"}
      ];
      getInvestmentsAcquisitionsByCompanies(CompaniesList, table);
      insertPartnerships(table);
      insertSubsidiaries(table);
      doneCallback();
    }

    if (table.tableInfo.id == "Categories") {
      var CategoriesList = [
        {CompanyNameJOIN:"99",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"19pay",SubCategory:"",Category:""},
  {CompanyNameJOIN:"3D Media",SubCategory:"",Category:""},
  {CompanyNameJOIN:"A8 Digital Music",SubCategory:"",Category:""},
  {CompanyNameJOIN:"ABEJA",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Accelight Networks",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Adero",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Adexa",SubCategory:"",Category:""},
  {CompanyNameJOIN:"AdInnovation",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Agility Communications",SubCategory:"",Category:"Others"},
  {CompanyNameJOIN:"Aiming",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Air2Web",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Airbus",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Akoustic Arts",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Algolux",SubCategory:"",Category:"Others"},
  {CompanyNameJOIN:"Alibaba",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Allegro.AI",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Alpaca",SubCategory:"",Category:""},
  {CompanyNameJOIN:"AlpacaJapan",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Alphabet Energy",SubCategory:"Energy production",Category:"Electrification"},
  {CompanyNameJOIN:"AmazonCS",SubCategory:"Charging Station",Category:"Electrification"},
  {CompanyNameJOIN:"AmazonS",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Ambee (1st Consult Technologies)",SubCategory:"",Category:""},
  {CompanyNameJOIN:"AmeriCredit",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Anaeropharma Science",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Anagog",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Annuncio Software",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Anthera Pharmaceuticals",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Antrim Design Systems",SubCategory:"",Category:""},
  {CompanyNameJOIN:"AOS Mobile",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Aperto Networks",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Apex.AI",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"Apollo Voice",SubCategory:"VPA",Category:"Connected"},
  {CompanyNameJOIN:"Apollo Voice Assistant",SubCategory:"",Category:""},
  {CompanyNameJOIN:"AppyParking",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Ardana Bioscience",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Argo AI",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"ArrayComm",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Aryballe Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"ASTES4",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Astro Malaysia Holdings Berhad",SubCategory:"",Category:""},
  {CompanyNameJOIN:"AT&T",SubCategory:"Car External Connections",Category:"Connected"},
  {CompanyNameJOIN:"AtomicTangerine",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Audible",SubCategory:"Entertainment",Category:"Connected"},
  {CompanyNameJOIN:"Audioburst",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Aurora",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"AutoAI",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Autobiz.fr",SubCategory:"Marketplace",Category:"Others"},
  {CompanyNameJOIN:"Autobutler",SubCategory:"",Category:""},
  {CompanyNameJOIN:"AutoFi",SubCategory:"Financial Services",Category:"Others"},
  {CompanyNameJOIN:"AutoGravity",SubCategory:"e-commerce",Category:"Others"},
  {CompanyNameJOIN:"Automobile Craiova",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Autonomic",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"AutoSpot",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Autotalks",SubCategory:"Wireless Technology",Category:"Connected"},
  {CompanyNameJOIN:"AvantGo",SubCategory:"Internet",Category:"Connected"},
  {CompanyNameJOIN:"Axiata",SubCategory:"",Category:""},
  {CompanyNameJOIN:"BAIC BJEV",SubCategory:"Electric Vehicles",Category:"Electrification"},
  {CompanyNameJOIN:"Baidu",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"BarterTrust.com",SubCategory:"",Category:"Others"},
  {CompanyNameJOIN:"Beat",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Ben & Frank",SubCategory:"",Category:""},
  {CompanyNameJOIN:"BeneStream",SubCategory:"",Category:""},
  {CompanyNameJOIN:"BeXcom Korea",SubCategory:"e-commerce",Category:"Others"},
  {CompanyNameJOIN:"BioAmber",SubCategory:"Industry",Category:"Others"},
  {CompanyNameJOIN:"BioMimetic Therapeutics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"bitFlyer",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Black Girls CODE",SubCategory:"Software",Category:"Others"},
  {CompanyNameJOIN:"Blacklane",SubCategory:"Car Hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Blackmore Sensors and Analytics",SubCategory:"Lidar solution",Category:"Autonomous"},
  {CompanyNameJOIN:"Blue Vision Labs",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Bluegogo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"BMW",SubCategory:"Electric Vehicles",Category:"Electrification"},
  {CompanyNameJOIN:"Bolt",SubCategory:"Micro Mobility",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"BoostWorks",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Bosch",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Boxbot",SubCategory:"Last mile delivery",Category:"Autonomous"},
  {CompanyNameJOIN:"Brandtrack",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Breeze",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Brigad",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Bright Automotive",SubCategory:"Car Manufacturer",Category:"Electrification"},
  {CompanyNameJOIN:"Broadlane",SubCategory:"Supply Chain",Category:"Others"},
  {CompanyNameJOIN:"Bus.com",SubCategory:"Bus sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Butterfield Fulcrum",SubCategory:"",Category:""},
  {CompanyNameJOIN:"BYD",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Cadillac",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Cadre",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Cambrios Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Campus Pipeline",SubCategory:"Software",Category:"Others"},
  {CompanyNameJOIN:"Caocao Chuxing",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Caocao Zhuanche",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Cape Wind",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Capital Analytics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Capy Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Car Next Door",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Cara Therapeutics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Carbon",SubCategory:"3D Printing",Category:"Others"},
  {CompanyNameJOIN:"carClub",SubCategory:"e-commerce",Category:"Others"},
  {CompanyNameJOIN:"Cardiac Dimensions",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Careem",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"CARFIT",SubCategory:"Big Data",Category:"Connected"},
  {CompanyNameJOIN:"Cargomatic",SubCategory:"",Category:""},
  {CompanyNameJOIN:"CARIZY",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Caroobi",SubCategory:"Car Marketplace",Category:"Others"},
  {CompanyNameJOIN:"carpooling.com",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Carventura",SubCategory:"Car Sales Platforms",Category:"Others"},
  {CompanyNameJOIN:"Carventura SAS",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Carwow",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Cascade Corporation",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Catalytic Solutions",SubCategory:"Pollution Technology",Category:"Others"},
  {CompanyNameJOIN:"CATL",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"Cermaq",SubCategory:"",Category:""},
  {CompanyNameJOIN:"CETITEC",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Chainalysis",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Challenge Media Group",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Chargemaster",SubCategory:"Charging Solution",Category:"Electrification"},
  {CompanyNameJOIN:"ChargePoint",SubCategory:"Charging Station",Category:"Electrification"},
  {CompanyNameJOIN:"Chargetrip",SubCategory:"Others",Category:"Electrification"},
  {CompanyNameJOIN:"Chariot",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Checkars",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Cherry",SubCategory:"",Category:""},
  {CompanyNameJOIN:"China Unicom",SubCategory:"Telecommunication",Category:"Others"},
  {CompanyNameJOIN:"Chordia Therapeutics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"CINQS",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"CINTEO GmbH",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Civil Maps",SubCategory:"Navigation",Category:"Connected"},
  {CompanyNameJOIN:"Claroty",SubCategory:"Cybersecurity",Category:"Others"},
  {CompanyNameJOIN:"Cleenup",SubCategory:"Car Cleening",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"ClimaCell",SubCategory:"",Category:""},
  {CompanyNameJOIN:"CloudCar",SubCategory:"Cloud",Category:"Connected"},
  {CompanyNameJOIN:"Cohesive Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Coinbase",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Commerx Corp.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Complex Polygon",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Conekta",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Continental",SubCategory:"Autonomy enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"Coord",SubCategory:"Platform",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Coskata",SubCategory:"Energy production",Category:"Electrification"},
  {CompanyNameJOIN:"Crowd Realty",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Cruise",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"Cswitch",SubCategory:"",Category:""},
  {CompanyNameJOIN:"CureApp",SubCategory:"",Category:""},
  {CompanyNameJOIN:"CyberHeart",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Daihatsu",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Daimler",SubCategory:"",Category:""},
  {CompanyNameJOIN:"DaimlerADS",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"DaimlerCS",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Data Enlighten",SubCategory:"Space Travel",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"DataChassi DC AB",SubCategory:"",Category:""},
  {CompanyNameJOIN:"DataScore",SubCategory:"",Category:""},
  {CompanyNameJOIN:"deCarta",SubCategory:"Navigation",Category:"Connected"},
  {CompanyNameJOIN:"Deepglint",SubCategory:"Car External Connections",Category:"Connected"},
  {CompanyNameJOIN:"DeepMap",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
  {CompanyNameJOIN:"Dejima",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Delphi",SubCategory:"Autonomy enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"Delta ID",SubCategory:"Identity Management",Category:"Connected"},
  {CompanyNameJOIN:"DeNA",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"Desktop Metal",SubCategory:"3D Printing",Category:"Others"},
  {CompanyNameJOIN:"Devialet",SubCategory:"",Category:""},
  {CompanyNameJOIN:"D-ID",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Didi Chuxing",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"DiscGenics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Disney",SubCategory:"Entertainment",Category:"Connected"},
  {CompanyNameJOIN:"Dominos",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"DriveNow GmbH & Co. KG",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Droom Technology",SubCategory:"",Category:""},
  {CompanyNameJOIN:"DSP Concepts",SubCategory:"Sounds sensor",Category:"Autonomous"},
  {CompanyNameJOIN:"eBags.com",SubCategory:"",Category:""},
  {CompanyNameJOIN:"EDS (Electronic Data Systems)",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Elementary Robotics",SubCategory:"Robot",Category:"Others"},
  {CompanyNameJOIN:"e-LogiT",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Embark",SubCategory:"Public Transportation app",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Embodied, Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Emerald Automotive",SubCategory:"",Category:""},
  {CompanyNameJOIN:"eMov",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Empower Energies Inc.",SubCategory:"Solar Energy",Category:"Electrification"},
  {CompanyNameJOIN:"Encryptix",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Enel",SubCategory:"Charging Station",Category:"Electrification"},
  {CompanyNameJOIN:"Enevate",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"Engie",SubCategory:"Charging Station",Category:"Electrification"},
  {CompanyNameJOIN:"Engs Commercial Finance",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Entuity",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Envia Systems",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"eRoom Technology",SubCategory:"Entreprise Software",Category:"Others"},
  {CompanyNameJOIN:"Eurus Energy Holdings",SubCategory:"",Category:""},
  {CompanyNameJOIN:"EVgo",SubCategory:"Charging Station",Category:"Electrification"},
  {CompanyNameJOIN:"EXest",SubCategory:"",Category:""},
  {CompanyNameJOIN:"FA Tech Co Ltd.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Fair",SubCategory:"Car Leasing",Category:"Others"},
  {CompanyNameJOIN:"feezu.cn",SubCategory:"Car Sharing Solution",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Fiat Chrysler Automobiles",SubCategory:"",Category:""},
  {CompanyNameJOIN:"FinitePaths Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Flexitech Holding",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Flinc",SubCategory:"Micro Mobility",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"flinc GmbH",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"FlixBus",SubCategory:"Bus sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"FlixMobility",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Fonderie Aluminium Cleon",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Forciot",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Ford",SubCategory:"Electric Vehicles",Category:"Electrification"},
  {CompanyNameJOIN:"Free2Move",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Free2Move Paris",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Freedom Robotics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"freee",SubCategory:"",Category:""},
  {CompanyNameJOIN:"FreeWire Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Gadauto",SubCategory:"",Category:""},
  {CompanyNameJOIN:"GaN Systems",SubCategory:"Battery technology",Category:"Electrification"},
  {CompanyNameJOIN:"Garantibil",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Garmin",SubCategory:"Entertainment",Category:"Connected"},
  {CompanyNameJOIN:"Gaudena",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Gengo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"GeoDigital",SubCategory:"Lidar solution",Category:"Autonomous"},
  {CompanyNameJOIN:"Geometric Intelligence",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Getaround",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Gett",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Girls Who Code",SubCategory:"Software",Category:"Others"},
  {CompanyNameJOIN:"GM Financial",SubCategory:"",Category:""},
  {CompanyNameJOIN:"GOJEK",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Google",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"GottaPark",SubCategory:"Parking",Category:"Connected"},
  {CompanyNameJOIN:"Grab",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Graphcore",SubCategory:"AI components",Category:"Others"},
  {CompanyNameJOIN:"Grohmann Engineering",SubCategory:"",Category:""},
  {CompanyNameJOIN:"H2scan",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Hans Glas",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Hap2U",SubCategory:"HMI",Category:"Connected"},
  {CompanyNameJOIN:"HDS Global",SubCategory:"e-commerce",Category:"Others"},
  {CompanyNameJOIN:"HERE Technologies",SubCategory:"Navigation",Category:"Connected"},
  {CompanyNameJOIN:"Heycar",SubCategory:"e-commerce",Category:"Others"},
  {CompanyNameJOIN:"Hibernia Networks",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Hino Ottawa-Gatineau",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Hitch",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Hive",SubCategory:"e-scooter",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"HoloEyes",SubCategory:"",Category:""},
  {CompanyNameJOIN:"HuaweiADS",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"HuaweiCEC",SubCategory:"Car External Connections",Category:"Connected"},
  {CompanyNameJOIN:"HuaweiS",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Hubject",SubCategory:"Charging Solution",Category:"Electrification"},
  {CompanyNameJOIN:"Humanigen",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Hydrogenious Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"iBiquity Digital Corporation",SubCategory:"Connectivity",Category:"Connected"},
  {CompanyNameJOIN:"IBM",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"ICONICS",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Ignite Sports Media",SubCategory:"Software",Category:"Others"},
  {CompanyNameJOIN:"iKaaz",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Illuminate Labs",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Immotor",SubCategory:"e-scooter",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Infolibria",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Informative",SubCategory:"",Category:""},
  {CompanyNameJOIN:"INRIX",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Intel",SubCategory:"Autonomy enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"Intelligent Apps",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Intelligent Apps (mytaxi)",SubCategory:"Ride Hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Intuition Robotics",SubCategory:"",Category:"Others"},
  {CompanyNameJOIN:"Ionic Materials",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"Ionity",SubCategory:"Charging Station",Category:"Electrification"},
  {CompanyNameJOIN:"iPierian",SubCategory:"",Category:""},
  {CompanyNameJOIN:"iRidge",SubCategory:"",Category:""},
  {CompanyNameJOIN:"iSpace China",SubCategory:"Space Travel",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"I-Tech",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Jaguar",SubCategory:"",Category:""},
  {CompanyNameJOIN:"JapanTaxi",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Jedlix",SubCategory:"",Category:""},
  {CompanyNameJOIN:"JIMU Intelligent",SubCategory:"",Category:""},
  {CompanyNameJOIN:"JLR",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"Joby Aviation",SubCategory:"e-Plane",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Journey Holding Corporation",SubCategory:"",Category:""},
  {CompanyNameJOIN:"JTOWER Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"JUMP Bikes",SubCategory:"",Category:""},
  {CompanyNameJOIN:"JustPark",SubCategory:"Parking",Category:"Connected"},
  {CompanyNameJOIN:"JX PRESS",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kalray",SubCategory:"Electronics",Category:"Others"},
  {CompanyNameJOIN:"Kamaz",SubCategory:"Trucks",Category:"Others"},
  {CompanyNameJOIN:"Kamcord",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kaufland",SubCategory:"Charging Station",Category:"Electrification"},
  {CompanyNameJOIN:"Keyfactor",SubCategory:"Identity Management",Category:"Connected"},
  {CompanyNameJOIN:"KH-Automation Projects GmbH",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kia Motors",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kii Corporation",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kinestral Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kinzan.com",SubCategory:"",Category:""},
  {CompanyNameJOIN:"KnowledgeNet",SubCategory:"e-learning",Category:"Others"},
  {CompanyNameJOIN:"Konfio",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Koolicar",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kuaidi Dache",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kudo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kyash",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kyriba",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Kyriba Japan",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Leo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Lidl",SubCategory:"Charging Station",Category:"Electrification"},
  {CompanyNameJOIN:"Life360",SubCategory:"Mobile Application",Category:"Connected"},
  {CompanyNameJOIN:"LifeRobotics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Liftit",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Lime",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Lincoln Motor Company",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Li-Tec Battery",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Livio Radio",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Lizardtech",SubCategory:"",Category:""},
  {CompanyNameJOIN:"LoiLo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Lotus Cars",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Luminar",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"Lunewave",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
  {CompanyNameJOIN:"Luxe",SubCategory:"",Category:""},
  {CompanyNameJOIN:"LUXI Co. Ltd.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"LuxN",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Lyft",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Lytx",SubCategory:"",Category:""},
  {CompanyNameJOIN:"macaron TAXI (KST Intelligence)",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Macro",SubCategory:"",Category:""},
  {CompanyNameJOIN:"MainVest",SubCategory:"",Category:""},
  {CompanyNameJOIN:"MakeMusic, Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"MakinaRocks",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Maluuba",SubCategory:"Machine learning",Category:"Others"},
  {CompanyNameJOIN:"mana.bo Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Manganese Bronze Holdings PLC",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Manthey-Racing",SubCategory:"",Category:""},
  {CompanyNameJOIN:"MapAnything",SubCategory:"Software",Category:"Others"},
  {CompanyNameJOIN:"Mapillary",SubCategory:"Map",Category:"Connected"},
  {CompanyNameJOIN:"Markforged",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Mascoma",SubCategory:"Energy production",Category:"Electrification"},
  {CompanyNameJOIN:"Matternet",SubCategory:"Delivery",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Maxwell Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"May Mobility",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
  {CompanyNameJOIN:"Mazda Motor Corp.",SubCategory:"Car Manufacturer",Category:"Others"},
  {CompanyNameJOIN:"Mcity",SubCategory:"AD Test simulator",Category:"Autonomous"},
  {CompanyNameJOIN:"MDGo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Medcom Sp. z o.o.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"MELCO Hydronics & IT Cooling S.p.A.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Mesh Korea",SubCategory:"Logistic",Category:"Others"},
  {CompanyNameJOIN:"Messung Group",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Metawave",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Metawave Corporation",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
  {CompanyNameJOIN:"MICIN Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Microsoft",SubCategory:"Cloud/Data Platforms",Category:"Others"},
  {CompanyNameJOIN:"Mighty AI",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Migo",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Miles",SubCategory:"Social Plateform",Category:"Connected"},
  {CompanyNameJOIN:"Mind Palette",SubCategory:"",Category:""},
  {CompanyNameJOIN:"MineSense Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Mister Auto",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Mitsubishi Electric Klimat Transportation Systems S.p.A",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Mitsubishi Motors",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Mobile Go",SubCategory:"Food services",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Mobileum",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Mobileye",SubCategory:"Autonomy enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"mobilityX",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Mobvoi",SubCategory:"VPA",Category:"Connected"},
  {CompanyNameJOIN:"Moca",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Modulated Imaging",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Moixa Technology",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Momenta",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
  {CompanyNameJOIN:"Momentum Dynamics Corp",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Money Forward",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Moneytree",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Monstar Lab",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Moovit",SubCategory:"Transportation info",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Motivate",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Muse & Co",SubCategory:"",Category:""},
  {CompanyNameJOIN:"MyCityWay",SubCategory:"Digital Platform",Category:"Others"},
  {CompanyNameJOIN:"Mycroft",SubCategory:"VPA",Category:"Connected"},
  {CompanyNameJOIN:"NanoSteel",SubCategory:"Nano Technology",Category:"Others"},
  {CompanyNameJOIN:"Nanotech Partners",SubCategory:"",Category:""},
  {CompanyNameJOIN:"NASA",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"Nauto",SubCategory:"AI",Category:"Autonomous"},
  {CompanyNameJOIN:"Navistar",SubCategory:"Trucks",Category:"Others"},
  {CompanyNameJOIN:"Nema Labs",SubCategory:"",Category:""},
  {CompanyNameJOIN:"NEO RETRO",SubCategory:"",Category:""},
  {CompanyNameJOIN:"NeoPhotonics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"NetLogic Microsystems",SubCategory:"",Category:""},
  {CompanyNameJOIN:"NeurogesX",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Nexu",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Ninja Van",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Northvolt",SubCategory:"Energy production",Category:"Electrification"},
  {CompanyNameJOIN:"Nubimetrics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Nuvve",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Nvidia",SubCategory:"Autonomy enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"NxtPhase",SubCategory:"",Category:""},
  {CompanyNameJOIN:"NxtWave Communications",SubCategory:"",Category:""},
  {CompanyNameJOIN:"ObjectVideo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Oceans Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"ofo",SubCategory:"Bike-Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Ogwugo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Ola",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"OLAM International",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Omada",SubCategory:"Identity Management",Category:"Connected"},
  {CompanyNameJOIN:"OmniSonics Medical Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Opel Group",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Opel Special Vehicles",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Open Harbor",SubCategory:"",Category:""},
  {CompanyNameJOIN:"OpenSynergy",SubCategory:"Software",Category:"Connected"},
  {CompanyNameJOIN:"Orocobre",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Otonomo",SubCategory:"Car External Connections",Category:"Connected"},
  {CompanyNameJOIN:"Otto",SubCategory:"",Category:""},
  {CompanyNameJOIN:"OVO Energy",SubCategory:"",Category:""},
  {CompanyNameJOIN:"OYO",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Panacea Pharmaceuticals",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Panasonic",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"Parallel Domain",SubCategory:"AD Test simulator",Category:"Autonomous"},
  {CompanyNameJOIN:"ParkMobile",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Parkmobile Group Europe",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"ParkTAG",SubCategory:"Parking",Category:"Connected"},
  {CompanyNameJOIN:"PayByPhone Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Peloton Technology",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Peninsula Pharmaceuticals",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Perbix",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Perceptive Automata",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
  {CompanyNameJOIN:"Percepto",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Pivotal",SubCategory:"Entreprise Software",Category:"Others"},
  {CompanyNameJOIN:"Pixim",SubCategory:"Hardware",Category:"Others"},
  {CompanyNameJOIN:"Pizza Hut",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Plaid inc",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Platypus Technology",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Plumtree Software",SubCategory:"Entreprise Software",Category:"Others"},
  {CompanyNameJOIN:"PointGrab",SubCategory:"",Category:""},
  {CompanyNameJOIN:"PontaMedia",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Porsche",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Port Medical",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Power Vehicle Innovation",SubCategory:"",Category:""},
  {CompanyNameJOIN:"PowerCell Sweden",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Powerex",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Powerhive",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Powermat Technologies",SubCategory:"Wireless Charging",Category:"Electrification"},
  {CompanyNameJOIN:"PowerShare",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Preferred Networks",SubCategory:"AI",Category:"Connected"},
  {CompanyNameJOIN:"Prescient Markets",SubCategory:"Electronics",Category:"Others"},
  {CompanyNameJOIN:"Prism Entertainment",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Producteca",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Promethera Biosciences",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Prophesee",SubCategory:"",Category:""},
  {CompanyNameJOIN:"proteanTecs",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Proterra",SubCategory:"EV Bus",Category:"Electrification"},
  {CompanyNameJOIN:"PROTON Holdings",SubCategory:"Car Manufacturer",Category:"Others"},
  {CompanyNameJOIN:"PTV Group",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Pulsar Technology",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Quake Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"QualcommAE",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"QualcommCEC",SubCategory:"Car External Connections",Category:"Connected"},
  {CompanyNameJOIN:"Quantum Biosystems",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Quantum Signal",SubCategory:"",Category:""},
  {CompanyNameJOIN:"QuantumScape",SubCategory:"Energy storage",Category:"Electrification"},
  {CompanyNameJOIN:"R3",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Rally",SubCategory:"Bus sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Rapid Motor Vehicle Company",SubCategory:"",Category:""},
  {CompanyNameJOIN:"RareJob Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Raven Biotechnologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Realtime Robotics",SubCategory:"Software",Category:"Others"},
  {CompanyNameJOIN:"Recogni",SubCategory:"",Category:""},
  {CompanyNameJOIN:"REE",SubCategory:"",Category:""},
  {CompanyNameJOIN:"REGiMMUNE Corporation",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Reliance Jio Infocomm Limited",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Reliance Motor Car Company",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Renewable Energy Trust Capital",SubCategory:"",Category:""},
  {CompanyNameJOIN:"RenRenChe",SubCategory:"commerce",Category:"Others"},
  {CompanyNameJOIN:"Respiro",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Retty",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Rever",SubCategory:"Social Plateform",Category:"Connected"},
  {CompanyNameJOIN:"Revl",SubCategory:"Action Cam",Category:"Others"},
  {CompanyNameJOIN:"Revv",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Ridecell",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"RidePal",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Rimac",SubCategory:"Electric Vehicles",Category:"Electrification"},
  {CompanyNameJOIN:"Rimac Automobili",SubCategory:"EV Components",Category:"Electrification"},
  {CompanyNameJOIN:"Rioport",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Ritase",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Rivian Automotive",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"Riviera Tool LLC",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Rover",SubCategory:"",Category:""},
  {CompanyNameJOIN:"SAIPS",SubCategory:"Machine learning",Category:"Others"},
  {CompanyNameJOIN:"Sakti3",SubCategory:"Battery technology",Category:"Electrification"},
  {CompanyNameJOIN:"Samsung SDI",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"Sansan",SubCategory:"Entreprise Software",Category:"Others"},
  {CompanyNameJOIN:"Saxo Bank",SubCategory:"Financial Services",Category:"Others"},
  {CompanyNameJOIN:"Scania",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Scoop Technologies",SubCategory:"P2P Carpooling",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"SDC Materials,Inc.",SubCategory:"Nano Technology",Category:"Others"},
  {CompanyNameJOIN:"Seak",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Security Bank Corporation",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Sequence Design",SubCategory:"Software",Category:"Others"},
  {CompanyNameJOIN:"Serenex",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Setsuyo Astec Corp.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Seurat Technologies",SubCategory:"Printing Solution",Category:"Others"},
  {CompanyNameJOIN:"Seven Seas Technologies Group",SubCategory:"",Category:""},
  {CompanyNameJOIN:"ShareNow",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Shell",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Shenyang Brilliance JinBei Automobile",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Shift",SubCategory:"Car Marketplace",Category:"Others"},
  {CompanyNameJOIN:"Shouqi Zhixing",SubCategory:"e-scooter",Category:"Electrification"},
  {CompanyNameJOIN:"Sidecar Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Siemens",SubCategory:"Car External Connections",Category:"Connected"},
  {CompanyNameJOIN:"Sila Nanotechnologies",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"Silicon Wave",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Silvercar",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"SiRF Technology",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Sirrus",SubCategory:"Material",Category:"Others"},
  {CompanyNameJOIN:"Sital Technology",SubCategory:"Software",Category:"Others"},
  {CompanyNameJOIN:"sitateru",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Skurt",SubCategory:"Car Rental",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Skybox Security",SubCategory:"",Category:""},
  {CompanyNameJOIN:"SLAMcore",SubCategory:"Spatial AI",Category:"Others"},
  {CompanyNameJOIN:"SMARTCAMP Co.,Ltd.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Snapeee",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Softbank",SubCategory:"",Category:""},
  {CompanyNameJOIN:"SolarCity",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Solid Power",SubCategory:"Battery technology",Category:"Electrification"},
  {CompanyNameJOIN:"SolidEnergy Systems",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"Solve MIT",SubCategory:"",Category:"Others"},
  {CompanyNameJOIN:"Sonexa Therapeutics",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Sonus Networks",SubCategory:"",Category:""},
  {CompanyNameJOIN:"SoundHound Inc.",SubCategory:"Car Control",Category:"Connected"},
  {CompanyNameJOIN:"Spare",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Spin",SubCategory:"Scooter Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Splyt",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Spotify",SubCategory:"Entertainment",Category:"Connected"},
  {CompanyNameJOIN:"Spring",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Spring Labs",SubCategory:"Financial Services",Category:"Others"},
  {CompanyNameJOIN:"Starship Technologies",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
  {CompanyNameJOIN:"StoreDot",SubCategory:"Batteries",Category:"Electrification"},
  {CompanyNameJOIN:"StradVision",SubCategory:"",Category:""},
  {CompanyNameJOIN:"StradVision, Inc",SubCategory:"ADAS",Category:"Autonomous"},
  {CompanyNameJOIN:"STRATIM Systems",SubCategory:"Fleet Management",Category:"Others"},
  {CompanyNameJOIN:"STRIVR",SubCategory:"VR training",Category:"Others"},
  {CompanyNameJOIN:"Strobe",SubCategory:"Lidar solution",Category:"Autonomous"},
  {CompanyNameJOIN:"Summit Power International Ltd.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Summon",SubCategory:"Car Hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Sunhill Technologies",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Sunlogics",SubCategory:"Solar Energy",Category:"Electrification"},
  {CompanyNameJOIN:"Swiftly",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Swipe Labs",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Swit",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Sylpheo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Symphony Communication Services",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Tantau Software",SubCategory:"e-commerce",Category:"Others"},
  {CompanyNameJOIN:"Taxify",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Tekion",SubCategory:"Machine learning",Category:"Others"},
  {CompanyNameJOIN:"Teknovus",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Telcontar",SubCategory:"Connectivity",Category:"Connected"},
  {CompanyNameJOIN:"Telogis",SubCategory:"Navigation",Category:"Others"},
  {CompanyNameJOIN:"Tencent",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"TeraLogic",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Terrafugia",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Terra-Gen Power",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Tesla",SubCategory:"Electric Vehicles",Category:"Electrification"},
  {CompanyNameJOIN:"The Markup",SubCategory:"",Category:""},
  {CompanyNameJOIN:"The Mobility House",SubCategory:"",Category:""},
  {CompanyNameJOIN:"ticketstreet",SubCategory:"",Category:""},
  {CompanyNameJOIN:"tiramizoo",SubCategory:"Delivery",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Tokyo Otaku Mode",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Tomtom",SubCategory:"Navigation",Category:"Connected"},
  {CompanyNameJOIN:"TradeBeam",SubCategory:"",Category:""},
  {CompanyNameJOIN:"TradeCard",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Tragara",SubCategory:"",Category:""},
  {CompanyNameJOIN:"TranSiC",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Transit",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"TransLoc",SubCategory:"Navigation",Category:"Connected"},
  {CompanyNameJOIN:"TravelCar",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Trillium Secure",SubCategory:"",Category:""},
  {CompanyNameJOIN:"TRINAMIC Motion Control",SubCategory:"",Category:""},
  {CompanyNameJOIN:"TTTech",SubCategory:"Electronics",Category:"Connected"},
  {CompanyNameJOIN:"Tula Technology",SubCategory:"ICE Technology",Category:"Electrification"},
  {CompanyNameJOIN:"TuneIn",SubCategory:"Entertainment",Category:"Connected"},
  {CompanyNameJOIN:"Turo",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"TVS Logistics Services",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Uber",SubCategory:"Ride hailing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Uber Advanced Technologies Group",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
  {CompanyNameJOIN:"Uber China",SubCategory:"",Category:""},
  {CompanyNameJOIN:"ubitricity",SubCategory:"",Category:""},
  {CompanyNameJOIN:"UDcast",SubCategory:"",Category:""},
  {CompanyNameJOIN:"United States Artists",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Univision Communications",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Urgent.ly Roadside Assistance",SubCategory:"Services platform",Category:"Connected"},
  {CompanyNameJOIN:"Ushr",SubCategory:"Navigation",Category:"Autonomous"},
  {CompanyNameJOIN:"UVeye",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Uzabase",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Valeo",SubCategory:"ADAS",Category:"Autonomous"},
  {CompanyNameJOIN:"Validated",SubCategory:"Ride Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Vantage Power",SubCategory:"Electric Engine",Category:"Electrification"},
  {CompanyNameJOIN:"Vaprema",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Varjo",SubCategory:"",Category:""},
  {CompanyNameJOIN:"VAYAVISION",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Velodyne LiDAR",SubCategory:"Autonomous vehicle",Category:"Autonomous"},
  {CompanyNameJOIN:"VeriSign",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Via",SubCategory:"Autonomous VAN/Trucks",Category:"Autonomous"},
  {CompanyNameJOIN:"Via Transportation, Inc.",SubCategory:"Shuttle Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Vincotech Holdings S.a.r.l.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Virent Energy Systems",SubCategory:"Energy provider",Category:"Electrification"},
  {CompanyNameJOIN:"Vodafone",SubCategory:"Car External Connections",Category:"Connected"},
  {CompanyNameJOIN:"Volocopter",SubCategory:"Air Mobility",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Volvo Cars Group",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Vontu",SubCategory:"Software",Category:"Others"},
  {CompanyNameJOIN:"VTXRM",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Vulog",SubCategory:"MaaS Platform",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Walmart",SubCategory:"Autonomy Enablers",Category:"Autonomous"},
  {CompanyNameJOIN:"Waymo",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"Waypoint Leasing Services",SubCategory:"",Category:""},
  {CompanyNameJOIN:"WayRay",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Wealthnavi",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Wejo",SubCategory:"Big Data",Category:"Connected"},
  {CompanyNameJOIN:"WeRide.ai",SubCategory:"AI",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"WeShare",SubCategory:"Car Sharing",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"what3words",SubCategory:"Navigation",Category:"Connected"},
  {CompanyNameJOIN:"WHILL",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Whyteboard",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Wind River",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"WirelessCar",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Xchange Leasing",SubCategory:"",Category:""},
  {CompanyNameJOIN:"xenodata lab",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Xevo",SubCategory:"Services",Category:"Connected"},
  {CompanyNameJOIN:"Xiaomi",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Xometry",SubCategory:"Manufacturing Solution",Category:"Others"},
  {CompanyNameJOIN:"Xtra, Inc.",SubCategory:"",Category:""},
  {CompanyNameJOIN:"YandexADS",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"YandexN",SubCategory:"Navigation",Category:"Connected"},
  {CompanyNameJOIN:"Yellowbrick Data",SubCategory:"Data Management",Category:"Others"},
  {CompanyNameJOIN:"Yeong Guan Energy",SubCategory:"",Category:""},
  {CompanyNameJOIN:"YesGraph",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Yestock",SubCategory:"Car Rental",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"Yoshi",SubCategory:"Cleaning and gas services",Category:"Connected"},
  {CompanyNameJOIN:"Zebra Imaging",SubCategory:"3D technology",Category:"Others"},
  {CompanyNameJOIN:"Zendrive",SubCategory:"Sensors",Category:"Connected"},
  {CompanyNameJOIN:"Zenuity",SubCategory:"AD Software",Category:"Autonomous"},
  {CompanyNameJOIN:"Zhidou",SubCategory:"Electric Vehicles",Category:"Electrification"},
  {CompanyNameJOIN:"Zipline",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Zola Electric",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Zolvers",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Zonar",SubCategory:"Fleet Management",Category:"Connected"},
  {CompanyNameJOIN:"ZoomCar",SubCategory:"Car Rental",Category:"Sharing/Subscription"},
  {CompanyNameJOIN:"ZRRO",SubCategory:"",Category:""},
  {CompanyNameJOIN:"Zum",SubCategory:"Child Transportation",Category:"Sharing/Subscription"}
      ];
      var categoriesTableData = [];
      for (var i = 0, len = CategoriesList.length; i < len; i++) {
        categoriesTableData.push({
          "company_name_JOIN": CategoriesList[i].CompanyNameJOIN,
          "subcategory": CategoriesList[i].SubCategory,
          "category": CategoriesList[i].Category
        });
      }
      table.appendRows(categoriesTableData);
    doneCallback();
  }

  };

  tableau.registerConnector(myConnector);

  $(document).ready(function() {
    $("#submitButton").click(function() {
      tableau.connectionName = "CrunchBase Feed";
      tableau.submit();
    });
  });
})();
